// JavaScript Document
que2=[{ans:3,que:'下列何者可以增加電腦文書檔案管理的效率？',ans1:'頁首設定',ans2:'頁碼設定',ans3:'有系統的檔名命名規則',ans4:'粗體字'},
{ans:1,que:'在進行文章編修時，下列那一項設定不會直接影響文章編修的操作？',ans1:'螢幕顏色的設定',ans2:'插入(Insert)/覆蓋(Replace)的設定',ans3:'左右邊界設定',ans4:'定位鍵(Tab)設定'},
{ans:1,que:'在 Open Office 套裝軟體內，何種軟體屬於文書處理軟體？',ans1:'Writer',ans2:'Impress',ans3:'Calc',ans4:'Draw'},
{ans:2,que:'在 Open Office 套裝軟體內，何種軟體屬於簡報軟體？',ans1:'Writer',ans2:'Impress',ans3:'Calc',ans4:'Draw'},
{ans:2,que:'下列何者不是作業系統？',ans1:'Windows',ans2:'Oracle',ans3:'Unix',ans4:'Linux'},
{ans:3,que:'下列那一套電子郵件系統還能兼具有「管理行事曆」的功能？',ans1:'Outlook Express',ans2:'Netscape',ans3:'Outlook',ans4:'cc:Mail'},
{ans:1,que:'那一個軟體不可以直接把檔案轉換為網頁？',ans1:'Acrobat',ans2:'Word',ans3:'PhotoImpact',ans4:'PowerPoint'},
{ans:4,que:'那一種文件我們可以利用 Word 完成？',ans1:'建築設計圖製作',ans2:'翻譯英文文章',ans3:'製作動畫',ans4:'網頁製作'},
{ans:2,que:'以下那一個行為在 Internet 環境中是違法的？',ans1:'交友',ans2:'買賣大補帖',ans3:'下載軟體',ans4:'聊天'},
{ans:3,que:'下列那一套軟體為電子郵件軟體？',ans1:'Word',ans2:'Excel',ans3:'Outlook',ans4:'Visio'},
{ans:3,que:'如果想把電子郵件寄送給許多人，卻又不想讓收件者彼此之間知道您寄給那些人，可以利用下列那一項功能做到？',ans1:'副本',ans2:'加密',ans3:'密件副本',ans4:'做不到'},
{ans:4,que:'為了讓郵件在傳送過程中不被駭客破壞，可以藉由電子郵件系統內之那一項功能來達成？',ans1:'壓縮',ans2:'反駭客',ans3:'密件副本',ans4:'加密'},
{ans:3,que:'如果想防止青少年進入一些像是色情或是暴力等網站，IE 瀏覽器可以藉由那一項功能做到？',ans1:'沒有這項功能',ans2:'加密',ans3:'分級',ans4:'分類'},
{ans:2,que:'當我們想把喜歡的網站位址保留下來以便未來可以輕易找到，Internet Explorer 可以藉由那一項功能做到？',ans1:'超連結',ans2:'我的最愛',ans3:'記錄',ans4:'我的標籤'},
{ans:4,que:'下列哪一種應用軟體不具有繪圖功能？',ans1:'Microsoft Word',ans2:'Microsoft Visio',ans3:'PhotoImpact',ans4:'Nero Express'},
{ans:2,que:'在 Microsoft Word 2003 環境中，若同時按下[Ctrl]+[O]鍵，則會執行下列哪一種動作？',ans1:'開新檔案',ans2:'開啟舊檔',ans3:'關閉檔案',ans4:'儲存檔案'},
{ans:3,que:'在 Microsoft Word 2003 環境中，若希望將一份文件重複列印 3 份，並自動按份數依序印出，則可在「檔案/列印」選項下選取下列哪一項功能來達成目的？',ans1:'反序列印',ans2:'幕後列印',ans3:'自動分頁',ans4:'雙面列印'},
{ans:1,que:'在 Microsoft Word 2003 環境中，若要以一個預先建置完成的通訊錄檔案來大量製作信封上的郵寄標籤，下列哪一種製作方法是最簡便者？',ans1:'合併列印',ans2:'範本',ans3:'版面設定',ans4:'表格'},
{ans:4,que:'若在 Microsoft Word 2003 環境中執行合併列印的動作時，由「插入合併欄位」功能所插入的欄位變數名稱「地址」會被下列何種符號框起來？',ans1:'?地址?',ans2:'{地址},',ans3:'[地址]',ans4:'《地址》'},
{ans:4,que:'在 Microsoft Word 2003 的「格式/欄」功能選項中，每一欄的寬度最小為幾個字元？',ans1:'0',ans2:'1',ans3:'2',ans4:'3'},
{ans:2,que:'在 Microsoft Word 2003 之「檔案/列印」功能選項中，若只要列印第 2 頁至第 8 頁時，應在對話盒中之「頁數」方框中輸入？',ans1:'2~8',ans2:'2-8',ans3:'2,8',ans4:'2:8'},
{ans:3,que:'若在 Microsoft Word 2003 環境中要使用二種不同格式的頁碼時，必須在不同頁碼之文件中插入下列何種符號？',ans1:'分頁',ans2:'欄',ans3:'分節',ans4:'分段'},
{ans:2,que:'下列應用軟體中，何者不具有文書處理功能？',ans1:'Microsoft Word',ans2:'Microsoft Access',ans3:'WordPad',ans4:'OpenOffice Writer'},
{ans:4,que:'在 Microsoft Word 2003 之「檔案/儲存」功能選項中，無法將檔案儲存為下列哪一種副檔名的檔案？',ans1:'.htm',ans2:'.dot',ans3:'.rtf',ans4:'.ppt'},
{ans:3,que:'下列有關 Microsoft Word 2003 的「表格」之敘述，何者為錯誤者？',ans1:'表格內之數字資料可以運算',ans2:'表格內之數字資料可以被排序',ans3:'表格內不可以有圖形',ans4:'表格內之儲存格可以被分割或合併'},
{ans:3,que:'在 Microsoft Word 2003 之「格式」內的「直書/橫書」功能選項中，下列哪一種類型的資料無法達到「直書/橫書」的功能？',ans1:'繁體中文字',ans2:'簡體中文字',ans3:'半形英文字',ans4:'全形英文字'},
{ans:2,que:'在 Microsoft Word 2003 的操作環境中，若要同時選取某一段文章的第二行第 3 至第 6 個字與第三行第 3 至第 6個字，則可將滑鼠先移至第二行第 3 個字後，再按下下列哪一個鍵、並拖曳滑鼠至第三行第 6 個字即可完成選取的動作？',ans1:'Ctrl 鍵',ans2:'Alt 鍵',ans3:'Shift 鍵',ans4:'Tab 鍵'},
{ans:4,que:'下列有關 Microsoft Word 2003 的敘述，何者錯誤？',ans1:'若某一段落被設定為「固定行高」且「行高 12pt」，而此段落的中文字卻被設定為「大小 24pt」，則只會顯示文字原高度的一半',ans2:'可以將圖文框插入文件的頁首部分內',ans3:'具有「Web 版面配置」模式，可供編輯網頁的操作環境',ans4:'建立表格時最多只能設定 32 個欄位'},
{ans:1,que:'下列有關 Microsoft Word 2003 的敘述中，何者為錯誤者？',ans1:'無法為文字設定註解',ans2:'可以改變檔案內容的顯示比例',ans3:'可以製作具有多欄的檔案內容',ans4:'可以使用書籤快速跳至所定義的位置處'},
{ans:2,que:'在 Microsoft Word 2010 中，開啟由 Microsoft Word 2003 所建立的.doc 檔案時，在文件視窗標題列會出現下列哪項文字？',ans1:'安全模式',ans2:'相容模式',ans3:'Word 97-2003 模式',ans4:'保護模式'},
{ans:2,que:'在 Microsoft Word 2010 中，有關「索引標籤、群組」的敘述，下列哪項錯誤？',ans1:'可新增索引標籤',ans2:'可調整「檔案」索引標籤的位置',ans3:'可隱藏預設的索引標籤',ans4:'不能隱藏預設的群組'},
{ans:4,que:'在 Microsoft Word 2010 中，下列何者不是「文字效果」所提供的效果？',ans1:'陰影',ans2:'反射',ans3:'光暈',ans4:'浮凸'},
{ans:2,que:'在 Microsoft Word 2010 中，若要從重疊的浮動圖片中，選取整張被其他圖片所覆蓋的圖片，在不移動圖片的情形下，運用下列哪項功能最為便捷？',ans1:'選取物件',ans2:'選取窗格',ans3:'進階尋找',ans4:'尋找'},
{ans:4,que:'在 Microsoft Word 2010 中，「螢幕擷取畫面」功能可以擷取下列哪些視窗畫面？',ans1:'所有最大化的視窗',ans2:'所有未最小化的開啟視窗',ans3:'除 Word 視窗外，所有最大化的視窗',ans4:'除 Word 視窗外，所有未最小化的開啟視窗'},
{ans:3,que:'在 Microsoft Word 2010 中，下列哪項合併列印可使用「更新標籤」功能？',ans1:'信件',ans2:'信封',ans3:'標籤',ans4:'目錄'},
{ans:2,que:'在 Microsoft Word 2010 中，下列哪項合併列印功能，不能使用目前文件作為主文件？',ans1:'信件',ans2:'標籤',ans3:'目錄',ans4:'電子郵件訊息'},
{ans:2,que:'在 Microsoft Word 2010 中，要將文件中的英文字母快速改為全形的字母，可使用下列哪項功能？',ans1:'字型',ans2:'大小寫轉換',ans3:'放大字型',ans4:'亞洲方式配置'},
{ans:1,que:'在 Microsoft Word 2010 中，若要翻譯特定的英文字，可按住下列哪一按鍵，再以滑鼠左鍵在單字上按一下，結果就會出現在「參考資料」窗格內？',ans1:'Alt',ans2:'Ctrl',ans3:'Shift',ans4:'Tab'},
{ans:2,que:'在 Microsoft Word 2010 中，根據 Word 預設值，圖片會在儲存檔案時，以何種解析度來壓縮影像？',ans1:'300ppi',ans2:'220ppi',ans3:'150ppi',ans4:'96ppi'},
{ans:2,que:'在 Microsoft Word 2010 中，「檔案」索引標籤中的「最近」功能，根據 Word 預設值能顯示最近曾經開啟的文件數量為何？',ans1:'20',ans2:'25',ans3:'15',ans4:'30'},
{ans:3,que:'在 Microsoft Word 2010 中，合併列印的「電子郵件訊息」，透過下列哪項來寄送電子郵件？',ans1:'Facebook',ans2:'Gmail',ans3:'Outlook',ans4:'LINE'},
{ans:4,que:'在 Microsoft Word 2010 中，佈景主題為一組格式設定選項，下列何者不是「佈景主題」所組成的項目？',ans1:'色彩',ans2:'字型',ans3:'效果',ans4:'圖片'},
{ans:2,que:'在 Microsoft Word 2010 中，下列哪個功能不會改變文字間的間距？',ans1:'最適文字大小',ans2:'字元比例',ans3:'字元間距',ans4:'分散對齊'},
{ans:1,que:'在Microsoft Word 2010中，若選取文件中的部分文字將其分為二欄，則Word會自動在文件中加入下列哪個符號？',ans1:'分節符號',ans2:'分欄符號',ans3:'分行符號',ans4:'定位符號'},
{ans:1,que:'在 Microsoft Word 2010 中，在整頁模式時若要將頁首頁尾區域展開，可在紙張上、下邊緣如何操作？',ans1:'按滑鼠左鍵兩下',ans2:'按滑鼠左鍵一下',ans3:'以滑鼠左鍵往上拖曳',ans4:'以滑鼠左鍵往下拖曳'},
{ans:2,que:'在 Microsoft Word 2010 中，「圖片效果」不具有哪項效果？',ans1:'光暈',ans2:'填滿',ans3:'浮凸',ans4:'立體旋轉'},
{ans:4,que:'在 Microsoft Word 2010 中，下列何者不是「設定圖片格式」的「反射」效果可調整之項目？',ans1:'大小',ans2:'距離',ans3:'模糊',ans4:'對比'},
{ans:4,que:'在 Microsoft Word 2010 中，製作「目錄」時，下列何者可作為「項目資料來源」？',ans1:'標號',ans2:'項目標記',ans3:'書籤',ans4:'樣式'},
{ans:2,que:'在 Microsoft Word 2010 中，製作紙張方向為直向及橫向同時存在的文件時，需在文件中插入下列哪個符號？',ans1:'分欄符號',ans2:'分節符號(下一頁)',ans3:'分頁符號',ans4:'文字換行分隔符號'},
{ans:4,que:'Mac OS 使用幾個點的多指觸控左右滑動來切換全螢幕操作視窗？',ans1:'1',ans2:'2',ans3:'3',ans4:'4'},
{ans:4,que:'Mac OS 中的 iWork 不包含以下那些應用軟體？',ans1:'Keynote',ans2:'Pages',ans3:'Numbers',ans4:'Words'},
{ans:3,que:'Mac OS 研發程式最常使用 Xcode IDE，其所使用的語言是？',ans1:'Java',ans2:'C#',ans3:'Objective-C',ans4:'C++'},
{ans:3,que:'下列哪一個程式語言依然還保存 pointer 的概念？',ans1:'Java',ans2:'C#',ans3:'Objective-C',ans4:'Basic'},
{ans:2,que:'Mac OS 使用幾個點的多指觸控是相當於 MS-Windows 快顯功能表的功能？',ans1:'1',ans2:'2',ans3:'3',ans4:'4'}]