// JavaScript Document
que3=[{ans:3,que:'下列何者是指電腦中所使用的中文字型，是依每一筆劃的起點、方向以及終點等資料儲存？',ans1:'矩陣法',ans2:'點字法',ans3:'線段法',ans4:'字根法。'},
{ans:1,que:'關於「中文內碼」的說明，下列何者正確？',ans1:'一字一碼，長度一定',ans2:'一字一碼，長度不定',ans3:'一字多碼，長度一定',ans4:'一字多碼，長度不定。'},
{ans:3,que:'下列作業系統中，何者沒有支援圖型化界面？',ans1:'OS/2',ans2:'UNIX',ans3:'MS-DOS',ans4:'Windows XP。'},
{ans:2,que:'電腦中，一個 24×24 點的中文字型，在記憶體中共佔用了多少位元組？',ans1:'48',ans2:'72',ans3:'64',ans4:'24。'},
{ans:1,que:'目前中文內碼(BIG-5)中，使用兩個位元組，其高位元組十六進位值均大於下列何值？',ans1:'80',ans2:'10',ans3:'40',ans4:'F0。'},
{ans:3,que:'下列何者是多人多工的作業系統？',ans1:'Windows',ans2:'CP/M',ans3:'UNIX',ans4:'MS-DOS。'},
{ans:3,que:'在「命令提示字元」下，無法執行下列那一種格式的檔案？',ans1:'.BAT 檔',ans2:'.EXE 檔',ans3:'.SYS 檔',ans4:'.COM 檔。'},
{ans:1,que:'下列那一種印表機一定無法列印中文字？',ans1:'菊輪式印表機',ans2:'噴墨式印表機',ans3:'雷射印表機',ans4:'點矩陣式印表機。'},
{ans:3,que:'何種副檔名的檔案其內容包含控制硬體操作的裝置資訊或指令檔？',ans1:'exe',ans2:'bat',ans3:'inf',ans4:'tmp。'},
{ans:2,que:'在 Windows XP 中，使用下列何種技術讓電腦能夠更容易辨識出此硬體裝置？',ans1:'PCMCIA',ans2:'Plug & Play',ans3:'IDE',ans4:'SCSI。'},

{ans:4,que:'以下那一個不是 Windows XP 提供的通訊協定？',ans1:'TCP/IP',ans2:'NetBEUI',ans3:'IPX/SPX 相容通訊協定',ans4:'NetRom。'},
{ans:1,que:'以下那一個不是在安裝 Windows XP 時必須要注意的要素？',ans1:'是否已安裝音效卡',ans2:'記憶體是否足夠',ans3:'CPU 速度是否為 233MHz 以上',ans4:'硬碟可用空間是否夠大。'},
{ans:2,que:'關於在「Windows XP 安裝 USB 介面的硬體」的敘述，下列何者錯誤？',ans1:'系統會自動偵測到硬體，並啟動「找到新硬體精靈」',ans2:'要關機才能將硬體接上連接埠',ans3:'不可接到 IEEE 1394 的連接埠',ans4:'USB 支援隨插即用。'},
{ans:2,que:'Windows XP 使用的長檔名，不能含下列那個字元？',ans1:'空白',ans2:'＊',ans3:'【',ans4:'＄。'},
{ans:2,que:'要使用下列那一組按鍵，可以顯示「開始」功能表？',ans1:'Alt+Shift',ans2:'Ctrl+Esc',ans3:'Ctrl+Alt',ans4:'Alt+Esc。'},
{ans:4,que:'Windows XP 使用的長檔名的檔案不能夠在下列那一種作業系統中被開啟？',ans1:'MS-DOS',ans2:'Windows NT',ans3:'OS/2',ans4:'UNIX。'},
{ans:4,que:'當 Windows XP 的長檔名轉成 8.3 格式時，會將主檔名的第幾個字元變成～符號？',ans1:'第 4 個',ans2:'第 5 個',ans3:'第 6 個',ans4:'第 7 個。'},
{ans:2,que:'在 Windows XP 下執行「命令提示字元」後，要切換視窗或全螢幕顯示模式，可以使用鍵盤？',ans1:'Ctrl+Shift',ans2:'Alt+Enter',ans3:'Ctrl+Tab',ans4:'Alt+F4。'},
{ans:3,que:'當要離開 Windows XP 並關閉電腦，以下何種方式為正確的方式？',ans1:'按 PC 上的 Reset 鍵',ans2:'關閉 PC 上的電源',ans3:'使用開始功能表的電腦關機指令',ans4:'按 Ctrl+Alt+Delete 鍵。'},
{ans:4,que:'若在 Windows XP 下開啟五個應用程式，並且要各自使用不同的輸入法？',ans1:'無法做到',ans2:'最多只能使用兩種輸入法',ans3:'最多可使用四種輸入法',ans4:'有提供此一功能。'},
{ans:1,que:'在 Windows XP 的「檔案總管」中之「我的電腦」圖示上按右鍵，並選擇快顯功能表中的「內容」，則會出現那個視窗？',ans1:'系統內容',ans2:'磁碟內容',ans3:'顯示內容',ans4:'控制台。'},
{ans:4,que:'如果要在 Windows XP 下輸入「法文」字，應該要如何操做？',ans1:'更換為法文鍵盤',ans2:'國別設定為法國',ans3:'輸入法設定為法文',ans4:'鍵盤語系設定為法文。'},
{ans:2,que:'Windows XP 的「媒體播放程式 Media Player」無法播放以下那一種格式的檔案？',ans1:'音樂 CD',ans2:'VCD',ans3:'AVI',ans4:'Wave 音效。'},
{ans:3,que:'Windows XP 在印表機的「內容」選擇「詳細資料」，要設定使用的連接埠，下列那一項不會出現在選擇清單下？',ans1:'LPT1',ans2:'File:',ans3:'PS/2',ans4:'COM1。'},
{ans:2,que:'在 Windows XP 的「控制台」，若選取「系統」下的「裝置管理員」，發現有任何裝置與別的裝置發生衝突，會在該裝置前面顯示什麼符號？',ans1:'問號',ans2:'驚歎號',ans3:'打Ｘ',ans4:'錢幣符號。'},
{ans:3,que:'當在 Windows XP 系統登入並鍵入密碼時，其大小寫不正確會導致什麼結果？',ans1:'仍可以進入 Windows XP',ans2:'進入Windows XP 的安全模式',ans3:'要求重新輸入密碼',ans4:'關閉 Windows XP 並重新開機。'},
{ans:2,que:'在 Windows XP 中，能保留原使用者之工作，並能切換到另一個使用者帳號，此功能為何？',ans1:'登入',ans2:'切換使用者',ans3:'登出',ans4:'重新啟動。'},
{ans:2,que:'作業系統的主要功能為記憶體管理、處理機管理、設備管理及下列那一項？',ans1:'資料管理',ans2:'I/O 管理',ans3:'中文管理',ans4:'程式管理。'},
{ans:3,que:'下列作業中，那一項並非作業系統所提供之功能？',ans1:'分時作業(Time-sharing)',ans2:'多工作業(Multitasking)',ans3:'程式翻譯作業(Language Translation)',ans4:'多工程式作業(Multi-programming)。'},
{ans:3,que:'作業系統(Operating System)之主要目的，是為了幫助使用者更有效率及更方便的使用電腦的硬體資源，下列那一項不是一種作業系統的名稱？',ans1:'Windows',ans2:'Linux',ans3:'PL/1',ans4:'UNIX。'},
{ans:3,que:'Windows XP 的檔案目錄是採用下列何種結構？',ans1:'直線狀',ans2:'環狀',ans3:'樹狀',ans4:'星狀。'},
{ans:4,que:'下列敘述何者不正確？',ans1:'BCD 碼使用一組 4 位元表示一個十進位制的數字',ans2:'通用漢字標準交換碼為目前我國之國家標準交換碼',ans3:'ASCII 碼為常用的文數字資料的編碼',ans4:'BIG-5 碼是中文的外碼。'},
{ans:3,que:'在中文資料處理中，兩種不同資料之傳送過程必須靠下列何種碼來傳送？',ans1:'輸入碼',ans2:'內碼',ans3:'交換碼',ans4:'輸出碼。'},
{ans:1,que:'下列那一個負責監督電腦系統工作？',ans1:'作業系統',ans2:'套裝程式',ans3:'應用程式',ans4:'編譯程式。'},
{ans:3,que:'何者非 Internet 存取的網路通訊協定？',ans1:'TCP/IP',ans2:'NETBEUI',ans3:'RFID',ans4:'UDP/IP。'},
{ans:3,que:'Windows XP 的檔案屬性不包含下列何者？',ans1:'唯讀',ans2:'隱藏',ans3:'共享',ans4:'保存。'},
{ans:3,que:'在 Linux 作業系統下，使用何種指令可以顯示目前的目錄？',ans1:'makdir',ans2:'fg',ans3:'pwd',ans4:'cat。'},
{ans:4,que:'關於 Windows XP 的「檔案總管」的敘述，何者為不正確？',ans1:'可以用來複製磁片',ans2:'可以用來製作格式',ans3:'可以用來尋找檔案',ans4:'可以用來分割硬碟區間。'},
{ans:3,que:'在 Windows XP 系統中，能暫時將 RAM 資訊存在硬體，讓系統處於待命且省電的狀態，此為何項功能？',ans1:'關機',ans2:'安全模式',ans3:'休眠',ans4:'重新啟動。'},
{ans:1,que:'對於 Windows XP 的「造字程式」的敘述，下列何者為真？',ans1:'可以造 TrueType 字',ans2:'可以造點陣字',ans3:'可以造 Adobe 字',ans4:'可以造向量字。'},
{ans:3,que:'要利用 Windows XP 的「撥號網路」上 Internet，必須安裝及設定下列那一個網路通訊協定？',ans1:'IPX/SPX',ans2:'NetBUEI',ans3:'TCP/IP',ans4:'DLC。'},
{ans:3,que:'在 Windows XP 的桌面上按一下滑鼠右鍵，並選擇「內容」指令，則會開啟控制台的那一個項目？',ans1:'系統',ans2:'字型',ans3:'顯示',ans4:'網路。'},
{ans:2,que:'Windows XP 中的長檔名檔案 ABCDEFGHIJKL.ABC，在 MS-DOS 6.22 下 DIR 時，會變成下列那一個檔案名稱？',ans1:'ABCDEFGH.ABC',ans2:'ABCDEF~1.ABC',ans3:'ABCDEF~L.ABC',ans4:'ABCDEFH1.ABC。'},
{ans:3,que:'在 Windows XP 下提供檔案共享，且只准許能檢視檔案資料但不准變更，則使用權限應設定為？',ans1:'完全控制',ans2:'變更',ans3:'讀取',ans4:'複製。'},
{ans:3,que:'在 Windows XP 的「系統工具」下，不具備下列何種功能？',ans1:'系統資訊',ans2:'清理磁碟',ans3:'公用程式管理員',ans4:'磁碟重組工具。'},
{ans:1,que:'若想要更改 Windows XP 開始功能表的內容，需要在何處設定？',ans1:'選取工作列的「開始」功能表，按右鍵再選取「內容」選項',ans2:'選取檔案總管的「編輯」',ans3:'選取控制台的「系統」',ans4:'選取工作列的「工作管理員」選項。'},
{ans:2,que:'在 Windows XP 中，若按一下滑鼠左鍵，卻出現按右鍵的快捷功能表指令，以下何者為可能的原因？',ans1:'滑鼠故障',ans2:'控制台的「滑鼠」設定，被切換主要及次要按鈕',ans3:'滑鼠的驅動程式設定有誤',ans4:'滑鼠未安裝。'},
{ans:3,que:'因為經常會在 Windows XP 下複製及刪除檔案，應定期執行下列何種程式，以整理硬碟空間，讓檔案能儘量在連續磁區中被存放？',ans1:'磁碟壓縮程式',ans2:'磁碟掃描工具',ans3:'磁碟重組工具',ans4:'病毒掃描程式。'},
{ans:2,que:'下列何種中文輸入法與拆碼無關？',ans1:'行列輸入法',ans2:'手寫輸入法',ans3:'大易輸入法',ans4:'倉頡輸入法。'},
{ans:4,que:'在 Windows XP 的「命令提示字元」視窗中，下列那一項目中所示兩個指令的功能不一樣？',ans1:'CHDIR 與 CD',ans2:'MKDIR 與 MD',ans3:'RENAME 與 REN',ans4:'VERIFY 與 VER。'},
{ans:4,que:'在 Windows XP 的「命令提示字元」視窗中，下列敘述何者錯誤？',ans1:'根目錄(Root)也是一個目錄，而且不能被刪除',ans2:'VER 指令用於顯示 Windows 版本',ans3:'RMDIR 所欲刪除之目錄必須是個空目錄，否則將會拒絕刪除',ans4:'如果根目錄下沒有 USR 這個子目錄(Subdirectory)就不能執行 MD \USR\ABC。'},
{ans:1,que:'何者為 Internet 的遠端登入(login)功能？',ans1:'telnet',ans2:'ping',ans3:'cmd',ans4:'crd。'},
{ans:3,que:'在 Windows XP 的「命令提示字元」視窗中，下達「COPY C:TEST.ABC D:*.TXT」指令後，以下敘述何者正確？',ans1:'D 磁碟會產生檔名為 TEST.ABC 的檔案',ans2:'C 磁碟檔名為 TEST.ABC 的檔案將會不存在',ans3:'D 磁碟會產生檔名為TEST.TXT 的檔案',ans4:'C 磁碟會產生檔名為 TEST.TXT 的檔案。'},
{ans:1,que:'數據機傳輸資料的速率之單位為何？',ans1:'bps(bit per second)',ans2:'Bps(Byte per second)',ans3:'Mps(Mega per second)',ans4:'Gps(Giga per second)。'},
{ans:4,que:'「注音輸入法」是依照文字的什麼輸入？',ans1:'字形',ans2:'字根',ans3:'字義',ans4:'字音。'},
{ans:4,que:'在 Windows XP 的「命令提示字元」視窗中，以下那一種不是可執行檔案的副檔名？',ans1:'.bat',ans2:'.exe',ans3:'.com',ans4:'.prg。'},
{ans:4,que:'在 Windows XP 的「命令提示字元」視窗中，使用 DEL 命令刪除某個檔案時，螢幕出現「存取被拒」訊息，表示此要被刪除的檔案屬性為下列何者？',ans1:'共享(Shared)檔案',ans2:'系統(System)檔案',ans3:'隱藏(Hidden)檔案',ans4:'唯讀(Read-Only)檔案。'},
{ans:1,que:'下列系統何者可幫助使用者管理硬體資源，使電腦發揮最大的效能？',ans1:'作業系統',ans2:'媒體',ans3:'資料系統',ans4:'編修系統。'},
{ans:2,que:'下列敘述，何者錯誤？',ans1:'程式執行、檔案存取等皆屬於作業系統服務範疇',ans2:'COBOL 及 BASIC 皆屬於作業系統軟體',ans3:'電腦系統包含硬體、作業系統、應用程式及使用者',ans4:'作業系統目的是為了更方便和更有效率的使用電腦。'},
{ans:2,que:'下列何者符合程式多工處理(Multiprogramming)的工作原理？',ans1:'處理完一件工作後，才處理下一件工作',ans2:'電腦一次可以處理多個工作(Process)，但同一時段內只處理一件工作中的一部分',ans3:'同時段內處理所有工作的輸出入動作(I/O Operation)',ans4:'電腦同時段內可處理多件工作。'},
{ans:4,que:'使用直譯器(Interpreter)將程式翻譯成機器語言的方式，下列敘述何者正確？',ans1:'直譯器與編譯器(Compiler)翻譯方式一樣',ans2:'先翻譯成目的碼再執行之',ans3:'在鍵入程式的同時，立即翻譯並執行',ans4:'依行號順序，依序翻譯並執行。'},
{ans:3,que:'下列何者不屬於系統軟體？',ans1:'公用程式(Utility)',ans2:'作業系統(Operating System)',ans3:'會計系統(Accounting System)',ans4:'編譯程式(Compiler)。'},
{ans:1,que:'在安裝介面卡時，若 PC 內已有其他介面卡，則應該注意 I/O 位址、IRQ 及下列那一項是否相衝突？',ans1:'DMA',ans2:'Baud Rate',ans3:'Packet Size',ans4:'Frame Size。'},
{ans:2,que:'下列敘述何者正確？',ans1:'編譯器(Compiler)可編譯應用程式，故屬於應用軟體',ans2:'會計系統輔助會計作業，屬於應用軟體',ans3:'作業系統不能編譯程式，所以不是系統軟體',ans4:'作業系統(Operation System)可以編譯程式，所以屬於系統軟體。'},
{ans:2,que:'下列何者是一種高速的數位電話服務，可提高使用者連接 Internet 或公司區域網路(LAN)的速度？',ans1:'ADSL',ans2:'ISDN',ans3:'ISBN',ans4:'ETHERNET。'},
{ans:3,que:'在 Windows XP 中，如果執行「開始」功能表中的「登出」選項，會執行那一個動作？',ans1:'關閉 Windows XP',ans2:'重新啟動 Windows XP',ans3:'可以讓新的使用者登入',ans4:'讓電腦運作暫停可以省電。'},
{ans:4,que:'下列何者不是 Windows XP 中文版的「注音輸入法」所內定的鍵盤排列方式？',ans1:'標準',ans2:'倚天',ans3:'IBM',ans4:'王安。'},
{ans:1,que:'在 Linux 下發送電子郵件之指令為？',ans1:'mail',ans2:'vi',ans3:'mv',ans4:'vc。'},
{ans:3,que:'下列何者具有「動態連結函式庫及支援動態資料交換」功能？',ans1:'IDE',ans2:'OCR',ans3:'OLE',ans4:'OEM。'},
{ans:3,que:'以下的檔案格式中，何者無法在 Windows XP 的「媒體播放程式 Media Player」播放？',ans1:'.AVI',ans2:'.WAV',ans3:'.DAT',ans4:'.MID。'},
{ans:3,que:'在 Windows XP 中，如果想要選取全部檔案，應配合按住那一個按鍵，再選取檔案？',ans1:'Shift 鍵',ans2:'Ctrl 鍵',ans3:'Ctrl+A',ans4:'Shift+A。'},
{ans:4,que:'Windows XP 的「錄音機程式」，無法執行下列那一項功能？',ans1:'混音',ans2:'刪除片段聲音',ans3:'增加迴音',ans4:'儲存為 midi檔。'},
{ans:1,que:'在 Windows XP 下，下列何者為預設的字型？',ans1:'TrueType 字型',ans2:'點陣字型',ans3:'Adobe 字型',ans4:'向量字型。'},
{ans:3,que:'Windows XP 中所使用的「Media Player 10」程式，不具有下列那一項功能？',ans1:'複製 CD',ans2:'播放 CD',ans3:'轉錄成 MP4 檔案',ans4:'收聽網路廣播電台。'},
{ans:1,que:'以下何者為 CD 音效的取樣頻率？',ans1:'44.1KHz',ans2:'22.05KHz',ans3:'11.025KHz',ans4:'33.75KHz。'},
{ans:3,que:'以下何種原因會造成 Windows XP 的「錄音機程式」無法錄音？',ans1:'錄音品質使用 CD 品質',ans2:'使用 8 位元的音效卡',ans3:'麥克風的音量選項未選擇',ans4:'設定增加迴音。'},
{ans:4,que:'下列何者，在 Windows XP 下要使用連上 Internet，不一定要具備？',ans1:'安裝撥號配接卡',ans2:'安裝 TCP/IP 通訊協定',ans3:'安裝數據機',ans4:'使用 ISDN 線路。'},
{ans:2,que:'若在 Windows XP 下使用的是「標準的數據機」，則下列數據機的那一個選項無法被變更？',ans1:'連線速度',ans2:'數據機音量',ans3:'使用連接埠',ans4:'流量控制。'},
{ans:2,que:'在 Windows XP 系統中，下列何者不是正確安裝軟體的方法？',ans1:'將軟體光碟放入光碟機，系統會啟動自動安裝程式',ans2:'使用程式集的啟動選項',ans3:'使用開始功能表的執行選項',ans4:'使用控制台的新增／移除程式。'},
{ans:2,que:'在 WindowsXP 的「WordPad」軟體中，無法開啟下列那一種檔案類型？',ans1:'.txt',ans2:'.dbf',ans3:'.rtf',ans4:'.wri。'},
{ans:2,que:'在 Windows XP 下的製作備份程式，不能夠執行以下那一個操作？',ans1:'製作備份',ans2:'複製',ans3:'還原',ans4:'比較。'},
{ans:1,que:'想要在啟動 Windows 2000 Server 的時候啟動某一程式，可以將欲啟動的程式放在下列何處？',ans1:'啟動資料夾',ans2:'Win.ini 中',ans3:'系統的啟動',ans4:'使用者設定檔。'},
{ans:2,que:'在 Windows 的作業系統中，對於檔案的管理是採用何種結構？',ans1:'環狀',ans2:'樹狀',ans3:'網狀',ans4:'線狀。'},
{ans:1,que:'「台灣學術網路」簡稱為何？',ans1:'TANET',ans2:'TELNET',ans3:'INTERNET',ans4:'SEEDNET。'},
{ans:3,que:'下列何者不是作業系統的功能？',ans1:'輸出／入裝置的管理',ans2:'處理程序的管理',ans3:'輸入法的管理',ans4:'記憶體的管理。'},
{ans:3,que:'銀行的每半年一次的計息工作，適合使用下列那一種作業方式？',ans1:'即時處理作業',ans2:'交談式處理作業',ans3:'批次處15理作業',ans4:'平行式處理作業。'},
{ans:2,que:'硬碟結構中的系統區，檔案的真實位置被完整記錄在那一區中？',ans1:'硬碟分割區',ans2:'檔案配置區',ans3:'根目錄區',ans4:'啟動區。'},
{ans:1,que:'以下何者對於 Windows 2000 Server 關機程序描述正確？',ans1:'必須由「開始功能表」選關機',ans2:'可以由「開始/所有程式/啟動」選關機',ans3:'可以由系統的「啟動/關機」選關機',ans4:'可以直接關閉電源。'},
{ans:1,que:'下列系統何者可幫助使用者管理與使用硬體資源，使電腦發揮最大效能？',ans1:'作業系統',ans2:'輸出入系統',ans3:'資料系統',ans4:'編輯系統。'},
{ans:4,que:'在系統軟體中，透過軟體與輔助儲存裝置來擴展主記憶體容量，使數個大型程式得以同時放在主記憶體內執行的技術是？',ans1:'抽取式硬碟(Removable Disk)',ans2:'虛擬磁碟機(Virtual Disk)',ans3:'延伸記憶體(Extended Memory)',ans4:'虛擬記憶體(Virtual Memory)。'},
{ans:4,que:'下列有關「符合綠色環保電腦的條件」之敘述，何者不正確？',ans1:'必須是省電的',ans2:'必須符合人體工學',ans3:'必須是低污染，低輻射',ans4:'必須是木製外殼。'},
{ans:3,que:'以下何種內碼可以涵蓋世界各種不同文字？',ans1:'ASCII',ans2:'BIG-5',ans3:'UNICODE',ans4:'EBCDIC。'},
{ans:3,que:'下列的作業系統中，何者無法在 PC 上使用？',ans1:'SCO-UNIX',ans2:'Windows 2000',ans3:'VAX-11',ans4:'Windows XP。'},
{ans:4,que:'在一部 PC 中不能安裝下列那一種作業系統？',ans1:'Windows 2000',ans2:'Windows XP',ans3:'Linux',ans4:'AS400。'},
{ans:4,que:'以下何者不屬於網路作業系統(NOS)？',ans1:'UNIX',ans2:'Netware',ans3:'Windows 2000 Server',ans4:'Windows XP。'},
{ans:3,que:'在 Windows XP 中，下列那一個操作，可以顯示快顯功能表？',ans1:'按一下滑鼠左鍵',ans2:'按二下滑鼠左鍵',ans3:'按一下滑鼠右鍵',ans4:'按一下滑鼠左鍵並拖曳。'},
{ans:4,que:'在 Windows XP 中，如果要更改檔案的屬性，應在選取這個檔案後，按一下滑鼠右鍵，在快顯功能表中選取那一個指令？',ans1:'重新命名',ans2:'傳送到',ans3:'開啟',ans4:'內容。'},
{ans:2,que:'在 Windows XP 的「檔案總管」中，選取 C 磁碟中的一個資料夾，然後拖曳至 D 磁碟中，是執行下列那一個動作？',ans1:'搬移',ans2:'複製',ans3:'剪下',ans4:'刪除。'},
{ans:4,que:'在 Windows XP 的「檔案總管」中，選取 C 磁碟中的一個程式檔案，並拖曳至桌面上，會產生什麼結果？',ans1:'將檔案內容顯示桌面上',ans2:'這個操作不被允許',ans3:'刪除這個檔案',ans4:'將這個檔案搬移到桌面上。'},
{ans:2,que:'在 Windows XP 中，如果要在「檔案總管」新增一個資料夾，則應在那一個功能表中設定？',ans1:'檢視',ans2:'檔案',ans3:'工具',ans4:'編輯。'},
{ans:1,que:'在 Windows XP 中，如果要在「檔案總管」中顯示檔案名稱的副檔名，則應在那一個功能表中設定？',ans1:'工具',ans2:'檔案',ans3:'檢視',ans4:'編輯。'},
{ans:1,que:'在 Windows XP 中，如果要在「檔案總管」中顯示隱藏檔或系統檔，則應在那一個功能表中設定？',ans1:'工具',ans2:'檢視',ans3:'檔案',ans4:'編輯。'},
{ans:4,que:'在 Windows 2000 中，如果要更改顯示器的桌面圖案，應在「控制台」的「顯示器」中的那一個標籤下設定？',ans1:'設定',ans2:'效果',ans3:'外觀',ans4:'桌面。'},
{ans:1,que:'在 Windows XP 中，如果要更改顯示器的色彩解析度，應在「控制台」的「顯示器」中的那一個標籤下設定？',ans1:'設定值',ans2:'背景',ans3:'外觀',ans4:'效果。'},
{ans:3,que:'在 Windows XP 中，如果要更改顯示器的視窗色彩，應在「控制台」的「顯示」中的那一個標籤下設定？',ans1:'桌面',ans2:'螢幕保護裝置',ans3:'外觀',ans4:'設定值。'},
{ans:1,que:'在 Windows XP 中，在中文輸入狀態下，要在螢幕上顯示符號小鍵盤的預設值為按下列那一個按鍵？',ans1:'Ctrl+Alt+,',ans2:'Ctrl+Alt+M',ans3:'Ctrl+Alt+K',ans4:'Ctrl+Alt+L。'},
{ans:2,que:'在 Windows XP 中，在中文輸入狀態下，要重送前一次輸入的字串，預設值為按下列那一組按鍵？',ans1:'Ctrl+Alt+R',ans2:'Ctrl+Alt+G',ans3:'Ctrl+Alt+K',ans4:'Ctrl+Alt+L。'},
{ans:2,que:'在 Windows XP 中，在中文輸入法中，要切換不同的輸入法，預設值為按下列那一個按鍵？',ans1:'Ctrl+Space',ans2:'Ctrl+Shift',ans3:'Shift+Space',ans4:'Ctrl+Alt。'},
{ans:3,que:'在 Windows XP 中，在中文輸入法中，要切換全型和半型輸入，預設值為按下列那一個按鍵？',ans1:'Ctrl+Space',ans2:'Ctrl+Shift',ans3:'Shift+Space',ans4:'Ctrl+Alt。'},
{ans:1,que:'在 Windows XP 中，在中文輸入法中，要開啟和關閉中文輸入法，預設值為按下列那一個按鍵？',ans1:'Ctrl+Space',ans2:'Ctrl+Shift',ans3:'Shift+Space',ans4:'Ctrl+Alt。'},
{ans:4,que:'關於「網路」之敘述，下列何者錯誤？',ans1:'Windows XP 可以設定為對等式架構',ans2:'Windows2000 是一種主從式架構',ans3:'在 Windows XP 中可以設定直接以纜線連接',ans4:'在 Windows XP 中一定要透過網路才能上網。'},
{ans:3,que:'在 Windows XP 系統中，具有系統管理員的身份，其屬於何種群組？',ans1:'User',ans2:'Guest',ans3:'Administrators',ans4:'Replicator。'},
{ans:1,que:'在 Windows XP 中，若要使用全球資訊網(WWW)，必須在網路中設定那一種通訊協定？',ans1:'TCP/IP',ans2:'IPX/SPX',ans3:'NetBUEI',ans4:'DLC。'},
{ans:2,que:'在 Windows XP 中，要依裝置類型來檢視電腦中的硬體裝置，應該在「控制台」中的「系統」的那一個項目查看？',ans1:'一般',ans2:'裝置管理員',ans3:'硬體設定檔',ans4:'效能。'},
{ans:2,que:'在 Windows XP 中所使用的 TrueType 字型，其檔案類型為下列那一個？',ans1:'.sys',ans2:'.ttf',ans3:'.ini',ans4:'.fon。'},
{ans:4,que:'在 Windows XP 中，如果想要重新安排硬碟上的檔案及未使用的空間，使程式執行速度加快應該執行以下那一個程式？',ans1:'磁碟清理程式',ans2:'磁碟掃描工具',ans3:'磁碟壓縮工具',ans4:'磁碟重組程式。'},
{ans:1,que:'在 Windows XP 中，用來搜尋硬碟，並列出可以安全刪除的暫時檔、Internet 快取檔與不必要的程式檔，以協助釋放硬碟空間，應該執行以下那一個程式？',ans1:'清理磁碟程式',ans2:'磁碟掃描工具',ans3:'磁碟壓縮工具',ans4:'磁碟重組程式。'},
{ans:2,que:'在 Windows XP 中，用以檢查硬碟的邏輯與實體錯誤，並修復受損區域，應該執行以下那一個程式？',ans1:'磁碟清理程式',ans2:'檢查磁碟程式',ans3:'磁碟壓縮工具',ans4:'磁碟重組程式。'},
{ans:1,que:'在 Windows XP「檔案總管」中，以滑鼠要選取不連續的檔案，必須要配合？',ans1:'Ctrl 鍵',ans2:'Alt 鍵',ans3:'Shift 鍵',ans4:'Tab鍵。'},
{ans:3,que:'在 Windows XP 中，若要移除已安裝的「附屬應用程式」，應在下列何者中執行？',ans1:'「控制台」中的系統',ans2:'「控制台」中的使用者',ans3:'「控制台」中的「新增/移除程式」',ans4:'「控制台」中的「協助工具選項」。'},
{ans:4,que:'在 Windows XP 中，如果在「開始」功能表中，使用「搜尋/電腦」的操作，是用以下列何者做為尋找的對象？',ans1:'群組名稱',ans2:'IP 位址',ans3:'網域名稱',ans4:'電腦名稱。'},
{ans:2,que:'在 Windows XP 中，如果連按二次 Ctrl+Alt+Del，會發生以下何者狀況？',ans1:'重新開機',ans2:'出現工作管理員視窗',ans3:'關機',ans4:'不會發生任何改變。'},
{ans:2,que:'在 Windows 2003 Server 的環境中，下列何種服務是「可以配置自己的公開金鑰基礎結構，運用公開金鑰基礎結構，您可以設定標準的技術，如智慧卡登入功能、用戶端驗證、保護電子郵件、數位簽章及保護連線能力」？',ans1:'系統工具',ans2:'憑證服務',ans3:'協助工具服務',ans4:'保密服務。'},
{ans:1,que:'如果要在 Windows XP 的「網路上的芳鄰」中顯示本機電腦的名稱是「SEVER」，則進入到「控制台／系統」，在電腦名稱標籤中按下變更按鈕，應於下列那一個項目設定？',ans1:'電腦名稱',ans2:'組態',ans3:'工作群組',ans4:'電腦說明。'},
{ans:1,que:'在 Windows XP 中，要查詢本機電腦在網路上的 TCP/IP 組態設定值，應使用那一個指令？',ans1:'ipconfig',ans2:'ping',ans3:'route',ans4:'telnet。128. (B'},
{ans:4,que:'在 Windows XP 中，用以使用 TCP/IP 協定中的 TELNET 協定登入到網路上另一部主機，可以使用以下那一個指令？',ans1:'net telnet',ans2:'ftp',ans3:'route',ans4:'telnet。'},
{ans:1,que:'在 Windows XP 中，如何在「檔案總管」中得知 C 磁碟的容量大小？',ans1:'選取 C 磁碟後，再選取「檔案」功能表中的「內容」',ans2:'選取 C 磁碟後，再選取「檢視」功能表中的「詳細資料」',ans3:'選取 C 磁碟後，再選取「檢視」功能表中的「資料夾選項」',ans4:'選取 C 磁碟後，再選取「檢視」功能表中的「重新整理」。'},
{ans:2,que:'在 Windows XP 中，如果對硬碟進行格式化，則該硬碟可使用的檔案格式為下列何者？',ans1:'FAT16',ans2:'NTFS',ans3:'EFS',ans4:'DOS。'},
{ans:4,que:'在 Windows XP 中，如果要檢視本機的 IP 位址、子網路遮罩、預設的通訊閘等設定，應執行下列那一個程式？',ans1:'ping',ans2:'route',ans3:'net',ans4:'ipconfig。'},
{ans:2,que:'在 Windows XP 中「檔案總管」中，如果在刪除一個檔案時，不想讓檔案移至資源回收筒，則應使用以下那一個按鍵？',ans1:'Delete',ans2:'Shift+Delete',ans3:'Alt+Delete',ans4:'Ctrl+Delete。'},
{ans:1,que:'在 Windows XP 中，如果同時開啟多個應用程式視窗，可以使用以下那一個按鍵來切換作用中的視窗？',ans1:'Alt+Tab',ans2:'Ctrl+Tab',ans3:'Shift+Tab',ans4:'Tab。'},
{ans:3,que:'在 Windows XP 中，要關閉一個作用中的視窗，可以使用以下那一個按鍵？',ans1:'F4',ans2:'Shift+F4',ans3:'Alt+F4',ans4:'Ctrl+F4。'},
{ans:4,que:'在啟動 Windows 2000 時，若想以「安全模式」啟動，則應在出現 Windows 第一個畫面時，按一下那一個按鍵，再選取「安全模式」選項？',ans1:'F5',ans2:'F6',ans3:'F7',ans4:'F8。'},
{ans:3,que:'在 Windows XP 中，如果想要設定超過 15 分鐘未使用電腦時，要自動關閉監視器，則應在下列何處設定？',ans1:'顯示',ans2:'協助工具選項',ans3:'電源管理',ans4:'系統。'},
{ans:4,que:'關於「在 Windows XP 中搜尋一個檔案」之敘述，下列何者錯誤？',ans1:'可以指定要搜尋的檔案大小範圍',ans2:'可以指定要搜尋的檔案修改日期範圍',ans3:'可以指定要搜尋的資料夾',ans4:'可以指定要搜尋的檔案屬性。'},
{ans:1,que:'在 Windows XP 中，如果想要截取整個螢幕成為一個圖案，應按一下那一個按鍵？',ans1:'PrintScreen',ans2:'Alt+P',ans3:'Ctrl+P',ans4:'Ctrl+Print Screen。'},
{ans:1,que:'在 Windows XP 中，如果要移除一個硬體的設定值，應在下列何處操作？',ans1:'控制台的「系統」',ans2:'控制台的「新增/移除程式」',ans3:'控制台的「協助工具選項」',ans4:'控制台的「加入新的硬體」。'},
{ans:2,que:'在 Windows XP 的「檔案總管」中，如果想要檢視檔案的修改日期，應選擇那一種檢視模式？',ans1:'清單',ans2:'詳細資料',ans3:'圖示',ans4:'並排。'},
{ans:3,que:'在 Windows XP 中，如果要查看網路上有那些電腦提供共用的資源，應使用那一個指令？',ans1:'net ver',ans2:'net use',ans3:'net view',ans4:'net init。'},
{ans:4,que:'在 Windows XP 中，如果要檢視系統的完整組態資訊，包含硬體資源、軟體環境等，可以使用以下那一個應用程式？',ans1:'檔案總管',ans2:'我的電腦',ans3:'系統監視程式',ans4:'系統資訊。'},
{ans:4,que:'下列敘述何者不是 Windows Server 2000 之重要核心元件「目錄服務(Active Directory)」的功能？',ans1:'簡化管理',ans2:'加強網路安全性',ans3:'擴充交互運作能力',ans4:'複雜化管理。'},
{ans:2,que:'在 Windows XP 的「檔案總管」中，如果選取一個檔案後，選取傳送到 A 磁碟 其功能相當於以下何者？',ans1:'在 A 磁碟中建立一個只到這個檔案的捷徑',ans2:'複製這個檔案到 A 磁碟',ans3:'由 A 磁碟中複製這個檔案到硬碟',ans4:'搬移這個檔案到 A 磁碟。'},
{ans:4,que:'在 Windows XP 中，若要使在桌面上已開啟的視窗能垂直並排顯示，則應使用以下何者方式？',ans1:'在每個視窗右上角按二下',ans2:'在桌面上按一下右鍵，選取「新增」指令',ans3:'在「我的電腦」中設定',ans4:'在 Windows XP 的工作列上按一下右鍵，再選取「垂直並排」指令。'},
{ans:2,que:'在 Windows XP 中，如果要查詢一個中文字的內碼，應使用以下那一個程式？',ans1:'「控制台」中的字型',ans2:'字元對應表',ans3:'「控制台」中的「鍵盤」',ans4:'「控制台」中的「輸入法」。'},
{ans:4,que:'在 Windows XP 中，如果在「開始」功能表的「執行」中要啟動一個程式，下列何者有誤？',ans1:'要輸入完整的資料夾路徑和檔案名稱',ans2:'可直接執行 ping tw.yahoo.com',ans3:'可以執行「命令提示字元」視窗模式下的命令',ans4:'無法執行網路上任何的共享檔案。'},
{ans:2,que:'在 Windows XP 系統下，從哪裡可以還原已被刪除的檔案？',ans1:'控制台',ans2:'資源回收筒',ans3:'我的文件',ans4:'系統還原。'},
{ans:3,que:'在 Windows XP 系統下，「小畫家」所編輯的內容預設儲存成何種格式的檔案？',ans1:'.jpeg',ans2:'.gif',ans3:'.bmp',ans4:'.tif。'},
{ans:1,que:'在 Windows XP 系統中，從控制台的何處可檢視電腦硬體狀態？',ans1:'裝置管理員',ans2:'使用者帳戶',ans3:'地區及語言選項',ans4:'協助工具選項。'},
{ans:3,que:'在 Windows XP 系統下，「小畫家」的「復原」指令僅能記錄最近的幾個動作？',ans1:'1 個',ans2:'2 個',ans3:'3 個',ans4:'5 個。'},
{ans:4,que:'在 Windows XP 系統下，如何查看 CPU 現在的使用效能？',ans1:'系統',ans2:'排定的工作',ans3:'協助工具選項',ans4:'工作管理員。'},
{ans:2,que:'在 Windows XP 系統下，何種軟體不能插入圖片？',ans1:'WordPad',ans2:'記事本',ans3:'Excel 2003',ans4:'PowerPoint 2003。'},
{ans:4,que:'在 Windows XP 系統下，「記事本」沒有下列哪一項功能？',ans1:'更改字型大小',ans2:'變換字型',ans3:'字型樣式為粗體',ans4:'選擇文字顏色。'},
{ans:2,que:'在 Windows XP 系統的「檔案總管」中，下列何種儲存媒體(或位置)之檔案被刪除後將無法被「還原」？',ans1:'C磁碟',ans2:'軟式磁碟',ans3:'外接式硬碟',ans4:'桌面。'},
{ans:3,que:'何者不是作業系統？',ans1:'UNIX',ans2:'LINUX',ans3:'DBASE',ans4:'Windows XP。'},
{ans:4,que:'在 Windows XP 系統下，「控制台」內中之何種功能可用來安裝新的輸入法？',ans1:'字型',ans2:'鍵盤',ans3:'系統',ans4:'地區及語言選項。'},
{ans:1,que:'在 Windows XP 系統下，「控制台」內中之何種功能可用來安裝新的字型？',ans1:'字型',ans2:'鍵盤',ans3:'系統',ans4:'地區及語言選項。'},
{ans:3,que:'在 Windows XP 系統下，下列關於「使用者帳戶」之說明何者為非？',ans1:'一台電腦中可建立多個使用者帳號',ans2:'使用者帳號不一定要設密碼',ans3:'建立密碼可防止電腦病毒入侵',ans4:'電腦系統管理員有權限刪除其它使用者帳戶。'},
{ans:1,que:'在 Windows XP 系統下，預設是使用下列何者可將已安裝之應用程式從電腦中移除？',ans1:'使用控制台之「新增或移除程式」',ans2:'清理磁碟工具',ans3:'在桌面上刪除捷徑',ans4:'在「所有程式」或「程式集」列表中對該程式按右鍵選「刪除」。'},
{ans:1,que:'電腦網路通訊時，通訊雙方必須遵守的資料格式與時序稱為什麼？',ans1:'通訊協定',ans2:'安全協定',ans3:'資訊協定',ans4:'網路協定。'},
{ans:3,que:'在 Windows XP 作業環境下，一個新的硬碟須作下列哪一項工作才能開始使用？',ans1:'初始化',ans2:'系統化',ans3:'格式化',ans4:'清除化。'},
{ans:2,que:'在 Windows XP 系統下，若要以滑鼠選取連續多個檔案，必須以滑鼠先點取要選的第一個檔案後，再按住什麼鍵，用滑鼠在要選取的最後一個檔案點取一下？',ans1:'Ctrl',ans2:'Shift',ans3:'Alt',ans4:'Tab。'},
{ans:1,que:'在 Windows XP 系統下，若要以滑鼠選取不連續的檔案，必須以滑鼠先點取要選的第一個檔案，再按住什麼鍵，再用滑鼠點選第二個所要選取的檔案？',ans1:'Ctrl',ans2:'Shift',ans3:'Alt',ans4:'Tab。'},
{ans:1,que:'如何提高磁碟的存取效能？',ans1:'磁碟重組',ans2:'系統還原',ans3:'磁碟格式化',ans4:'刪除系統檔。'},
{ans:3,que:'在 Windows XP 系統下的「我的電腦」以何種檢視狀態呈現，可看見磁碟容量的大小？',ans1:'縮圖',ans2:'並排',ans3:'詳細資料',ans4:'清單。'},
{ans:1,que:'在 Windows XP 系統下，欲尋找檔案時可用何種方法？',ans1:'「開始」功能表中之「搜尋」',ans2:'「開始」功能表中之「執行」',ans3:'控制台',ans4:'資源回收筒。'},
{ans:4,que:'同樣像素的圖片(例如：800x600)，使用何種檔案格式儲存，所佔用的磁碟空間最多？',ans1:'JPG',ans2:'JPEG',ans3:'GIF',ans4:'BMP。'},
{ans:4,que:'如果電腦的速度變慢，增加下列何者的容量或速度大小將不會加快電腦反應速度？',ans1:'CPU',ans2:'隨機存取記憶體',ans3:'虛擬記憶體',ans4:'光碟機。'},
{ans:4,que:'在 Windows XP 系統中，由「命令提示字元」查看目錄資訊，以下敘述何者為非？',ans1:'「\」代表根目錄',ans2:'「..」代表上一層',ans3:'「C:\」代表 C 硬碟根目錄',ans4:'「.」代表下一層。'},
{ans:1,que:'下列何種字型於放大或縮小後不失真？',ans1:'向量型',ans2:'點陣型',ans3:'平面型',ans4:'立體型。'},
{ans:1,que:'在 Windows XP 系統中，若工作列上顯示目前有 3 個執行中視窗應用程式，則只要以鍵盤何種組合操作，即可任意切換到各個程式？',ans1:'Alt+Tab',ans2:'Ctrl+Alt',ans3:'Alt+Shift',ans4:'Ctrl+Shift。'},
{ans:4,que:'在 Windows XP 系統中，若想更改桌布圖案，可開啟「控制台」之何種功能？',ans1:'工作列和開始功能表',ans2:'使用者帳戶',ans3:'系統管理工具',ans4:'顯示。'},
{ans:3,que:'下列指令何者可以連線到遠方電子佈告欄(bbs)？',ans1:'cmd',ans2:'ping',ans3:'telnet',ans4:'dir。'},
{ans:4,que:'下列何者不是磁碟檔案配置格式？',ans1:'FAT16',ans2:'FAT32',ans3:'NTFS',ans4:'FETS。'},
{ans:2,que:'下列何種圖案於放大或縮小後不失真？',ans1:'點陣圖',ans2:'向量圖',ans3:'矩陣圖',ans4:'立體圖。'},
{ans:4,que:'在 Windows XP 系統中，「資源回收筒」最大容量為何？',ans1:'10MB',ans2:'100MB',ans3:'1GB',ans4:'可依磁碟容量設定百分比。'},
{ans:1,que:'在 Windows XP 系統中，按下什麼鍵會將目前顯示器所顯示的畫面儲存至「剪貼簿」內？',ans1:'Print Screen(PrtSc)',ans2:'Ctrl+Alt+Delete',ans3:'F4',ans4:'Caps Lock。'},
{ans:1,que:'在 Windows XP 系統，「文書編輯軟體」裡選擇「編輯／複製」選項後，被選取的文字或圖片會被暫放在哪裡？',ans1:'剪貼簿',ans2:'小畫家',ans3:'記事本',ans4:'WordPad。'},
{ans:4,que:'集線器(HUB)不包括下列哪一類？',ans1:'主動式(Active)',ans2:'被動式(Passive)',ans3:'智慧型(Intelligent)',ans4:'積極型(Aggressive)。'},
{ans:1,que:'在 Windows XP 系統中，下列何種圖示不能被刪除？',ans1:'資源回收筒',ans2:'我的電腦',ans3:'Internet Explorer',ans4:'Outlook。'},
{ans:4,que:'下列何者是 IBM 公司所產生的作業系統？',ans1:'OS X',ans2:'XP',ans3:'Vista',ans4:'OS 2。'},
{ans:3,que:'在 Windows Server 2000 作業系統中，可以讓使用者直接在電腦網路上架設 web 網站伺服器的軟體為何？',ans1:'ASP',ans2:'PHP',ans3:'IIS',ans4:'MySQL。'},
{ans:1,que:'在 Windows XP 系統中，啟動與關閉中文輸入法的快速鍵為何？',ans1:'Ctrl+Space',ans2:'Shift+Ctrl',ans3:'Alt+Shift',ans4:'Alt+Space。'},
{ans:3,que:'在 Internet 上做什麼是違法的？',ans1:'股票交易',ans2:'基金買賣',ans3:'下載未授權檔案',ans4:'用 msn 聊天。'},
{ans:4,que:'下列何種類型的電腦效能最佳？',ans1:'個人電腦',ans2:'工作站',ans3:'中大型電腦',ans4:'超級電腦。'},
{ans:1,que:'對於在 Internet 上的電腦而言，具有辨識獨一無二身份的資訊為何？',ans1:'IP 位址',ans2:'使用者名稱',ans3:'使用者密碼',ans4:'住家地址。'},
{ans:1,que:'下列何種作業系統最大的特點是開放原始程式碼給所有使用者？',ans1:'Linux',ans2:'Windows XP',ans3:'OS X',ans4:'Windows Vista。'},
{ans:1,que:'下列何種記憶體或輔助記體存取速度最快？',ans1:'SRAM',ans2:'DRAM',ans3:'Hard Disk',ans4:'Floppy。'},
{ans:4,que:'網路使用權限不包括下列何者？',ans1:'Administrators',ans2:'Guest',ans3:'Remote Desktop Users',ans4:'Anyone。'},
{ans:2,que:'在啟動 Windows XP 時，若尚未進入 Windows 系統之前，按下鍵盤上的何種功能鍵，可以選擇進入安全模式？',ans1:'F4',ans2:'F8',ans3:'F10',ans4:'F12。'},
{ans:4,que:'在 Windows 2003 Server 系統中，檔案名稱的命名最長只能容許多少字元？',ans1:'10',ans2:'100',ans3:'250',ans4:'255。'},
{ans:4,que:'在 Windows 2003 Server 系統中，提供何種多媒體播放工具，可以進行 CD 音樂播放及網路收音機功能？',ans1:'iTunes',ans2:'Power DVD',ans3:'iKala',ans4:'Media Player。'},
{ans:2,que:'下列何種副檔名的檔案對電腦來說是多餘的，刪除也不影響其原本運作？',ans1:'.exe',ans2:'.tmp',ans3:'.bat',ans4:'.ini。'},
{ans:3,que:'下列敘述何者為真？',ans1:'Linux 作業系統並不支援 TCP/IP 通訊協定，因此無法用來架設網站',ans2:'在視窗作業軟體中，滑鼠左右鍵的用法已經固定，不可以被修改',ans3:'在 Windows XP 視窗作業軟體中，能夠分別同時播放.MID 與.WAV 檔的音效',ans4:'所謂「多媒體電腦」是指電腦同時應用到許多新聞媒體的採訪報導。'},
{ans:2,que:'在 Windows XP 系統中，內建的影像剪輯軟體為何？',ans1:'威力四射',ans2:'Movie Maker',ans3:'Media Player',ans4:'會聲會影。'},
{ans:3,que:'在 Windows XP 系統下，所刪除的任何類型檔案都會被先丟到何處？',ans1:'控制台',ans2:'我的文件',ans3:'資源回收筒',ans4:'系統還原。'},
{ans:1,que:'連接電腦後不需重新啟動電腦即可使用的設備，為具有何種特性？',ans1:'plug and play',ans2:'input and output',ans3:'all in one',ans4:'pull and play。'},
{ans:3,que:'在 Windows XP 的環境下，您可以執行何種程式來釋放磁碟上的空間，它會搜尋硬碟並列出暫存檔、暫時的 Internet 檔案和可以安全刪除的非必要檔案？',ans1:'磁碟重組',ans2:'磁碟壓縮',ans3:'磁碟清除',ans4:'系統還原。'},
{ans:4,que:'下列何種物品不具備「智慧卡」(大小與信用卡差不多，其中含有內嵌的積體電路，可用以防止其儲存內容被篡改，進而保護各種個人資訊)功能？',ans1:'捷運悠遊卡',ans2:'自然人憑證',ans3:'健保卡',ans4:'無 IC 的提款卡。'},
{ans:4,que:'下列何種網路之連接規格的速度最快？',ans1:'MODEM 撥接',ans2:'ADSL',ans3:'T1',ans4:'T3。'},
{ans:4,que:'目前計算電腦記憶體(含輔助記憶體)容量大小的單位，下列何者最大？',ans1:'GB',ans2:'MB',ans3:'KB',ans4:'TB。'},
{ans:4,que:'下列何者不是 Windows XP 系統的桌面背景圖片可接受的副檔名？',ans1:'.bmp',ans2:'.gif',ans3:'.html',ans4:'.dwg。'},
{ans:1,que:'如果 Windows XP 沒有偵測到新的隨插即用裝置，則可能是裝置本身沒有正常運作、沒有正確安裝或者根本沒有安裝，此時，可以使用何種功能解決這些問題？',ans1:'裝置管理員',ans2:'協助工具選項',ans3:'新增或移除程式',ans4:'自動更新。'},
{ans:4,que:'何者非網路服務通訊協定？',ans1:'HTTP',ans2:'NNTP',ans3:'POP',ans4:'Netscape。'},
{ans:2,que:'UNIX 和 Windows XP 之間的比較敘述，下列何者為非？',ans1:'UNIX 廣泛使用於企業伺服器中，Windows XP 用於個人電腦',ans2:'Windows XP 會分辨指令的英文字母大小寫，UNIX 不會分辨',ans3:'Windows XP 是圖形使用者界面，UNIX 是文字界面',ans4:'UNIX 系統穩定性高於 Windows XP。'},
{ans:2,que:'在 Linux 作業系統下，使用何種指令可以複製檔案或目錄？',ans1:'mkdir',ans2:'cp',ans3:'alias',ans4:'echo。'},
{ans:3,que:'下列何者為網際網路服務提供商的英文縮寫？',ans1:'ASP',ans2:'PHP',ans3:'ISP',ans4:'DSP。'},
{ans:4,que:'想要使用 Giga-Fast Ethernet 至少要使用下列何種網路纜線等級？',ans1:'Category 4',ans2:'Category 4t',ans3:'Category 5',ans4:'Category 5e。'},
{ans:4,que:'下列哪個電信服務的頻寬最大？',ans1:'T1',ans2:'T3',ans3:'E1',ans4:'STM-1。'},
{ans:2,que:'大多數的 Linux 系統中，man page 指令以何種形式呈現資訊？',ans1:'使用以 X 為基礎的自訂應用程式',ans2:'使用 less 程式',ans3:'使用 Mozilla 網頁瀏覽器',ans4:'使用 Vi 編輯器。'},
{ans:3,que:'下列何者不屬於系統程式(System Program)？',ans1:'Compiler',ans2:'Linker',ans3:'Microsoft Office',ans4:'Loader。'},
{ans:4,que:'Linux 的指令模式下，如果想要儲存 ifconfig 的執行結果至文字檔(file.txt)，以供未來參考，同時想要覆蓋掉已存在的檔案資料，該如何下指令？',ans1:'ifconfig >> file.txt',ans2:'ifconfig < file.txt',ans3:'ifconfig | file.txt',ans4:'ifconfig > file.txt。'},
{ans:4,que:'Linux 使用者在 bash 下輸入 kill -9 2013 指令，假設該指令有效，則可能的執行結果為何？',ans1:'切斷 TCP port 2013的網路連結',ans2:'要求程序 ID 為 2013 的伺服器，重新載入設定檔',ans3:'顯示訊號為 2013 的程序，過去九天被終止的數量',ans4:'終結或停止程序 ID 為 2013 的程式。'},
{ans:4,que:'下列哪個目錄是 Linux 系統預設的資料暫存或快取的儲存目錄？',ans1:'/home',ans2:'/usr',ans3:'/boot',ans4:'/var。'},
{ans:1,que:'Linux 的 ls 指令可以顯示檔案或目錄的屬性，其中共有 10 個屬性，若第一個屬性顯示為「b」則表示為？',ans1:'周邊設備',ans2:'檔案',ans3:'目錄',ans4:'連結。'},
{ans:2,que:'在 Linux 中，可以按下哪一個組合鍵來中斷目前程式的執行？',ans1:'Ctrl+b',ans2:'Ctrl+c',ans3:'Ctrl+d',ans4:'Ctrl+z。'},
{ans:1,que:'下列哪個 Linux 指令無法用來改變檔案的權限？',ans1:'bc',ans2:'chmod',ans3:'chgrp',ans4:'chown。'},
{ans:3,que:'下列何種檔案系統的單一檔案之大小上限為 4GB？',ans1:'ext 2',ans2:'ext 3',ans3:'FAT32',ans4:'NTFS。'},
{ans:3,que:'要完全發揮 Windows 8.1 的多點觸控功能，觸控板必須至少支援幾點觸控？',ans1:'2',ans2:'3',ans3:'4',ans4:'5。'},
{ans:4,que:'(本題刪題)下列哪種 USB 內部接觸點為藍色標記？',ans1:'USB 1.1',ans2:'USB 2.0',ans3:'USB 3.0 Powered-B',ans4:'USB 3.0 StandardA。'},
{ans:2,que:'Windows 8.1 中，開啟常用鍵(含搜尋、分享、開始、裝置和設定)的觸控方式為何？',ans1:'捏合或伸展以進行縮放',ans2:'從邊緣撥動或滑動',ans3:'撥動以進行選取',ans4:'滑動以進行捲動。'},
{ans:3,que:'Linux 系統中，若是 test.sh 檔案屬性為「-rwxr-xr--」，要將檔案屬性改為「-r-xr-xr-x」，下列哪個指令可以完成？',ans1:'chmod u=rx test.sh',ans2:'chmod 755 test.sh',ans3:'chmod 555 test.sh',ans4:'chmod o-x test.sh。'},
{ans:3,que:'使用 iOS 7.x 的 Apple iPad，若要左右滑過螢幕來切換 App，則至少要同時使用幾點觸控來操作？',ans1:'2',ans2:'3',ans3:'4',ans4:'5。'},
{ans:1,que:'Windows 8.1 中，切換已開啟應用軟體的快捷鍵為何？',ans1:'Alt+Tab',ans2:'Alt+Shift',ans3:'Ctrl+Tab',ans4:'Alt+Shift。'},
{ans:2,que:'QR code 有提供「回」字定位點，所以可以任何角度掃描 。請問一個正常 QR Code 應該提供幾個定位點？',ans1:'2',ans2:'3',ans3:'4',ans4:'5。'},
{ans:2,que:'LCD 規格中「燭光/平方公尺」所指的是？',ans1:'對比率',ans2:'亮度',ans3:'可視角度',ans4:'反應時間。'},
{ans:4,que:'下列哪個作業系統不支援多點觸控？',ans1:'Mac OSX 10.9',ans2:'Windows 8.1',ans3:'Windows 7',ans4:'CentOS 6.0。'},
{ans:4,que:'多點觸控螢幕是使用哪一類的螢幕？',ans1:'電阻式觸控面板',ans2:'電容式觸控面板',ans3:'光學式觸控面板',ans4:'投射式電容觸控面板。'},
{ans:4,que:'下列哪個作業系統只能操作微軟的 Start App？',ans1:'Windows XP',ans2:'Windows 8.1',ans3:'Windows 7',ans4:'Windows RT。'},
{ans:4,que:'下列哪個作業系統開始支援動態磚操作？',ans1:'Windows XP',ans2:'Mac OSX 10.9',ans3:'Windows 7',ans4:'Windows 8。'},
{ans:1,que:'下列哪個作業系統不支援動態磚操作？',ans1:'Windows 7',ans2:'Windows Phone 8',ans3:'Windows 8.1',ans4:'Windows RT。'},
{ans:3,que:'下列哪個作業系統可在待機狀態下開啟相機功能，並將照片設定成輪播型態？',ans1:'Windows 7',ans2:'Windows Phone 7',ans3:'Windows 8.1',ans4:'Windows Phone 8。'},
{ans:3,que:'Windows 8.1 把滑鼠移動到桌面右上或右下角，呼叫出功能列，此功能列共有幾項功能可點選？',ans1:'3',ans2:'4',ans3:'5',ans4:'6。'},
{ans:3,que:'Windows 8 有一個 SnapView（子母畫面）的功能，但 SnapView 必須要多少解析度以上的螢幕才能使用？',ans1:'1024x768',ans2:'800x600',ans3:'1366x768',ans4:'1920x768。'},
{ans:1,que:'Windows 8 對視窗鍵 (Win'},
{ans:3,que:'Mac OSX 中，擷取全螢幕畫面的快捷鍵為何？',ans1:'PrintScreen',ans2:'Command+PrintScreen',ans3:'Command+Shift+3',ans4:'Command+Shift+PrintScreen。'},
{ans:2,que:'Windows 8 中，擷取工作視窗畫面的快捷鍵為何？',ans1:'PrintScreen',ans2:'Alt+PrintScreen',ans3:'Ctrl+PrintScreen',ans4:'Alt+Ctrl+PrintScreen。'},
{ans:4,que:'Mac OSX 10.9.x 中，強制重新啟動的快捷鍵為何？',ans1:'直接按下電源按鈕即可',ans2:'按住電源按鈕 5 秒',ans3:'按住電源按鈕 1.5 秒',ans4:'Command+Control+電源按鈕。'},
{ans:1,que:'直接把光纖接到用戶的家中之網路技術是？',ans1:'FTTH',ans2:'Cable Modem',ans3:'ADSL',ans4:'Ethernet。'},
{ans:2,que:'作業系統的搶救回復(recovery)機制中，檢查點(checkpoint)的作用是？',ans1:'檢查系統狀態的一致性',ans2:'加速系統回復的效率',ans3:'解決磁碟毀損後的回復問題',ans4:'改善資料異動執行的效率。'},
{ans:3,que:'以下哪一種區域網路標準，傳輸速率最慢？',ans1:'ATM',ans2:'Ethernet',ans3:'ARCnet',ans4:'FDDI。'},
{ans:4,que:'請問組譯程式(Assembler)與虛擬運算指令(Pseudo operation)的關係為何?',ans1:'組譯程式是用來連結虛擬運算指令',ans2:'虛擬運算指令可以編譯組譯程式',ans3:'虛擬運算指令編寫成的程式就是組譯程式',ans4:'組譯程式可用來編譯虛擬運算指令寫成的程式。'},
{ans:3,que:'下列何者不是智慧型手機作業系統？',ans1:'iOS',ans2:'Android',ans3:'Mongo',ans4:'Symbian。'},
{ans:1,que:'在 Linux 作業系統中，想要顯示目前已掛載檔案系統磁碟的 inode 使用狀況指令為何？',ans1:'df –i',ans2:'su –I',ans3:'free–i',ans4:'du –I。'},
{ans:2,que:'在 Linux 作業系統中，查看目前的網路設定指令為何？',ans1:'ipconfig',ans2:'ifconfig',ans3:'ipsetting',ans4:'ifsetting。'},
{ans:3,que:'在 Linux 作業系統中，修改檔案擁有者指令為何？',ans1:'chmod',ans2:'modown',ans3:'chown',ans4:'modch。'},
{ans:4,que:'下列有關 140.92.18.10/25 網段的敘述，何者是不正確的？',ans1:'可用 IP 數量為 126 個',ans2:'subnet mask：255.255.255.128',ans3:'network：140.92.18.0',ans4:'broadcast：140.92.18.128。'},
{ans:4,que:'下列關於固態硬碟 SSD(Solid State Disk)的敘述中，何者是錯誤的？',ans1:'無須驅動馬達、承軸或旋轉頭裝置，具有低耗電、低熱能的優點',ans2:'比起傳統的標準機械硬碟來說，SSD 所能承受的操作衝擊耐受度較高',ans3:'採用 DRAM或 Flash 取代傳統硬碟的碟片，讀寫速度快',ans4:'SSD 資料儲存密度高，故價格/每單位儲存容量也比傳統硬碟便宜。'},
{ans:2,que:'下列關於 XML(eXtensible Markup Language)的敘述中，何者是錯誤的？',ans1:'XML 提供一個跨平台、跨網路、跨程式語言的資料描述格式',ans2:'XML 和 HTML 一樣，都只能使用事先定義的標籤(tag)',ans3:'DTD 是用來規範 XML 文件的格式',ans4:'XSL 用來提供 XML 套用排版樣式之功能。'},
{ans:3,que:'下列何者是使得 Java 程式能夠完成跨平台(cross platform)運作的主要機制？',ans1:'例外處理',ans2:'多執行緒(multi-thread)',ans3:'虛擬機器',ans4:'物件導向。'},
{ans:1,que:'下列有關作業系統的操作中，何者是不需要使用系統呼叫(system call)？',ans1:'計算費伯納西數列(Fibonacci sequence)',ans2:'刪除一個行程(kill process)',ans3:'開啟一個檔案(open file)',ans4:'在螢幕上印出一些文字(screen output)。'},
{ans:1,que:'下列有關資料傳輸的介面，根據官方所公佈的規格，何者是傳輸速度最快的？',ans1:'SATA3',ans2:'eSATA',ans3:'USB3.0',ans4:'IEEE 1394b。'},
{ans:4,que:'下列有關「雲端運算」技術概念的敘述，何者是正確的？',ans1:'在電腦上進行雲狀式的數學運算',ans2:'空軍在雲層中利用電腦進行運算',ans3:'兩台電腦以藍芽互相傳送機密性資料',ans4:'透過網路連線取得遠端主機提供的服務。'},
{ans:1,que:'下列何者的傳輸媒介不是使用光纖？',ans1:'1000BaseT',ans2:'1000BaseSX',ans3:'FDDI',ans4:'10BaseF。'},
{ans:3,que:'下列行動通訊網路系統中，何者可提供之資料傳輸速率最快？',ans1:'GSM(Global System for Mobile communications)',ans2:'GPRS(General Packet Radio Service)',ans3:'HSDPA(High-Speed Downlink Packet Access)',ans4:'IS-95(Interim Standard 95)。'},
{ans:2,que:'下列何者不是目前 ISP(Internet Service Provider)所提供的服務？',ans1:'撥接上網',ans2:'提供作業系統安裝',ans3:'提供個人網頁',ans4:'提供電子郵件信箱。'},
{ans:1,que:'當使用者將 PC 開機時，下列敘述何者是正確的？',ans1:'部分的作業系統從磁碟被複製到記憶體',ans2:'部分的作業系統從記憶體被複製到磁碟',ans3:'部分的作業系統被編譯',ans4:'部分的作業系統被重新覆寫。'},
{ans:4,que:'辦公室中有數部電腦，將這些電腦以網路線與集線器(Hub)連接，以網路實體線路拓璞的概念來看，此種連接方式稱為？',ans1:'匯流排網路',ans2:'網狀網路',ans3:'環狀網路',ans4:'星狀網路。'},
{ans:4,que:'IPv6 位址是使用 128bit 的長度來標示電腦所在位址，所可以容許的位址個數是 IPv4 位址(位址長度為 32bit)的幾倍？',ans1:'4',ans2:'96',ans3:'24',ans4:'296。'},
{ans:1,que:'下列何者是不合法的 IPv6 位址寫法？',ans1:'1001::25de::cade',ans2:'1001:0DB8:0:0:0:0:1482:57ab',ans3:'1001:0d8b:85a3:083d:1319:82ae:0360:7455',ans4:'1001:DB8:2de::e46。'},
{ans:2,que:'IPv4 中提供使用私有 IP 位址空間的網路，例如 192.168.0.0-192.168.255.255 的區塊，下列何者是 IPv6 私有 IP 位址空間的寫法？',ans1:'FE80::1',ans2:'FEC0::2',ans3:'FF02::A001',ans4:'FF02::1:FF00:0101:0202。'},
{ans:3,que:'(本題刪題)在 Linux 系統中，用來設定檔案權限的設定值，可以使用文字型或數字型的宣告，下列那一組數字型的宣告，是不合法的？',ans1:'757',ans2:'1757',ans3:'5757',ans4:'2750。'},
{ans:2,que:'在 MAC OS 中使用「遠端桌面連線用戶端」的預設連接埠為？',ans1:'8080',ans2:'3389',ans3:'3660',ans4:'5900。'},
{ans:3,que:'GNU/Linux 的最高系統管理員帳號是？',ans1:'administrator',ans2:'admin',ans3:'root',ans4:'supervisor。'},
{ans:4,que:'在 Linux 系統中，可以使用 bash Shell Script 來撰寫簡單的 Script 程式。撰寫判斷結構指令時，使用 if 敘述開頭，結束敘述的指令為何？',ans1:'then',ans2:'end',ans3:'endif',ans4:'fi。'}]