// JavaScript Document
que1=[{ans:2,que:'磁碟每一面都是由很多同心圓圈組成，這些圓圈稱為什麼？',ans1:'磁區(Sector)',ans2:'磁軌(Track)',ans3:'磁頭(Head)',ans4:'磁柱(Cylinder)。',img:'' },
{ans:1,que:'若將一般電腦架構分為三大部份，是指那些部門？',ans1:'輸入／輸出／中央處理',ans2:'輸入／輸出／算術與邏輯運算',ans3:'輸入／輸出／記憶',ans4:'輸入／輸出／控制。',img:'' },
{ans:1,que:'螢幕上所顯示的字型，是以什麼組成的？',ans1:'點矩陣（Matrix）',ans2:'線條',ans3:'平面',ans4:'立體。',img:'' },
{ans:2,que:'資料傳輸可作雙向傳輸，但無法同時雙向傳輸的傳輸方法是下列哪一種方式？',ans1:'單工',ans2:'半雙工',ans3:'多工',ans4:'全雙工。',img:'' },
{ans:3,que:'螢幕的輸出品質好壞，視那項標準而定？',ans1:'輸出速度',ans2:'重量',ans3:'解析度',ans4:'大小。',img:'' },
{ans:2,que:'電腦主機與週邊設備間傳送資料的通道是？',ans1:'LCD',ans2:'I/O PORT(埠)',ans3:'RAM',ans4:'FDD。',img:'' },
{ans:2,que:'下列那一種網路架構，不屬於電腦網路架構？',ans1:'星狀架構(Star Structure)',ans2:'直接架構(Direct Structure)',ans3:'樹狀架構(Tree Structure)',ans4:'匯流排架構(Bus Structure)。',img:'' },
{ans:3,que:'印表機通常連接在主機的何處？',ans1:'COM1',ans2:'COM2',ans3:'LPT1',ans4:'Game Port。',img:'' },
{ans:2,que:'可直接存取1M 位元記憶體的微處理機，其位址線需要幾條？',ans1:'16',ans2:'20',ans3:'22',ans4:'24。',img:'' },
{ans:4,que:'下列何者係網路作業系統(NOS)？',ans1:'MS DOS',ans2:'MS Windows 3.1',ans3:'Apple Macintosh',ans4:'Novell/NetWare。',img:'' },
{ans:1,que:'後進先出(Last In First Out)的資料結構是？',ans1:'堆疊(Stack)',ans2:'佇列(Queue)',ans3:'樹(Tree)',ans4:'串列(List)。',img:'' },
{ans:3,que:'下列何者為「CAM」之意義？',ans1:'人工智慧',ans2:'電腦自動化',ans3:'電腦輔助製造',ans4:'電腦輔助設計。',img:'' },
{ans:4,que:'下列何種設備可將類比(Analog)信號與數位(Digital)信號互相轉換？',ans1:'前置處理機',ans2:'多工機',ans3:'傳真機',ans4:'數據機。',img:'' },
{ans:2,que:'機器週期可分為指令週期和執行週期：',ans1:'控制單元將指令中用來說明相關資料所儲存之位置的這一部份，存入位址暫存器',ans2:'控制單元從主記憶體中提取(Fetch)下一個所要執行的指令',ans3:'控制單元將指令予以解碼(Decode)',ans4:'控制單元將指令中用來說明要執行什麼動作的這一部份，存入指令暫存器 請問正確的指令週期的順序為？',ans1:'ABCD',ans2:'BCDA',ans3:'CBAD',ans4:'BADC。',img:'' },
{ans:1,que:'通常傳輸信號給近距離的週邊裝置（如印表機）是使用下列那一種方式？',ans1:'並列式傳輸',ans2:'序列式傳輸',ans3:'光纖傳輸',ans4:'電話機傳輸。',img:'' },
{ans:2,que:'唯讀記憶體簡稱為？',ans1:'RAM',ans2:'ROM',ans3:'COM',ans4:'POS。',img:'' },
{ans:2,que:'下列何種設備屬於WORM(Write Once Read Many)？',ans1:'Floppy disk',ans2:'CD-R',ans3:'Hard Disk',ans4:'MO。',img:'' },
{ans:1,que:'下列何者為主機與週邊設備溝通時不可或缺之管道',ans1:'匯流排(Bus)',ans2:'音效卡',ans3:'9-Pin 接頭',ans4:'數位轉換器(Digitizer)。',img:'' },
{ans:4,que:'下列何者對資料庫(Database)沒有寫入的動作？',ans1:'新增',ans2:'刪除',ans3:'更改',ans4:'查詢。',img:'' },
{ans:2,que:'設(a)為Bit；(b)為Record；(c)為Field；(d)為Character，則其在計算機內所佔空間的大小，由小到大之順序為？',ans1:'a,b,c,d',ans2:'a,d,c,b',ans3:'a,c,d,b',ans4:'a,d,b,c。',img:'' },
{ans:4,que:'CPU 的執行速度通常用下列何種單位表示？',ans1:'PPM',ans2:'BPS',ans3:'CPS',ans4:'MHZ。',img:'' },
{ans:1,que:'DPI 是用來衡量下列何者之單位？',ans1:'印表機列印品質',ans2:'磁碟精密度',ans3:'記憶體大小',ans4:'監視器品質。',img:'' },
{ans:3,que:'若利用8 位元來表達整數型態資料，且最左位元0 代表正數，1 代表負數，負數與正數間互為2 補數，則可表示之範圍為？',ans1:'0～255',ans2:'-127～128',ans3:'-128～127',ans4:'-255～0。',img:'' },
{ans:4,que:'下列何種設備之功能為將數位訊號與類比訊號互相轉換？',ans1:'多工器(Multiplexer)',ans2:'橋接器(Bridge)',ans3:'RS-232',ans4:'數據機(Modem)。',img:'' },
{ans:3,que:'由於位元(Bit)的單位太小了，所以藉由位元組(Byte)來代表更多的資料，而個人電腦中一個位元組等於多少位元？',ans1:'6',ans2:'7',ans3:'8',ans4:'9。',img:'' },
{ans:3,que:'由CPU 到主記憶或磁碟、磁鼓等I/O 設備，讀或寫一筆資料所需要的時間，一般稱為？',ans1:'搜尋時間(SearchTime)',ans2:'迴轉時間(Rotation Time)',ans3:'存取時間(Access Time)',ans4:'轉換時間(Transfer Time)。',img:'' },
{ans:4,que:'VLSI 之電子元件是指下列何者？',ans1:'電晶體',ans2:'真空管',ans3:'積體電路',ans4:'超大型積體電路。',img:'' },
{ans:3,que:'下列那一個名詞不是電腦術語中之描述速度單位？',ans1:'BPS',ans2:'MFWPS',ans3:'UPS',ans4:'MIPS。',img:'' },
{ans:1,que:'下列何者代表硬碟轉速的單位？',ans1:'RPM',ans2:'CPS',ans3:'MTBF',ans4:'LPM。',img:'' },
{ans:4,que:'下列何者不屬於應用軟體？',ans1:'文書處理(Word Processing)軟體',ans2:'電子試算表(SpreadSheet)軟體',ans3:'資料庫管理(Data Base Management)軟體',ans4:'載入(Loader)軟體。',img:'' },
{ans:4,que:'微秒(MicroSecond)是計量電腦速度的微小時間單位之一，一微秒等於',ans1:'千分之一秒',ans2:'十萬分之一秒',ans3:'萬分之一秒',ans4:'百萬分之一秒。',img:'' },
{ans:3,que:'具有易寫易懂之特性的是下列何種電腦語言？',ans1:'機器語言',ans2:'組合語言',ans3:'高階語言',ans4:'低階語言。',img:'' },
{ans:2,que:'將類似資料收集起來於一固定時間內一起處理的作業方式稱為',ans1:'連線處理',ans2:'批次處理',ans3:'即時處理',ans4:'雷射列印。',img:'' },
{ans:1,que:'下列何者不是應用軟體？',ans1:'作業系統',ans2:'庫存管理系統',ans3:'成績處理系統',ans4:'套裝軟體。',img:'' },
{ans:3,que:'下列應用軟體何者不是目前常見的資料庫管理軟體名稱？',ans1:'DB2',ans2:'ACCESS',ans3:'OUTLOOK',ans4:'ORACLE。',img:'' },
{ans:4,que:'下列何種儲存記憶體在電源關閉後記憶體內容不會消失？',ans1:'RAM',ans2:'SRAM',ans3:'DRAM',ans4:'Flash Memory。',img:'' },
{ans:4,que:'系統軟體主要乃協助使用者能更簡易、有效率的使用電腦系統；下列敘述何者不屬於系統軟體的內容？',ans1:'語言編譯程式',ans2:'磁碟作業系統',ans3:'公用程式',ans4:'進銷存管理系統。',img:'' },
{ans:2,que:'電腦系統在接收資料輸入，必須立即處理，並馬上輸出，最適合下列何種作業系統？',ans1:'多元處理(Multiprocessing)作業系統',ans2:'即時處理(Real-Time)作業系統',ans3:'網路(Network)作業系統',ans4:'多元程式(Multiprogramming)作業系統。',img:'' },
{ans:2,que:'使用直譯程式(Interpreter)將程式翻譯成機器語言的方式是？',ans1:'直譯程式(Interpreter)與編譯程式(Compiler)翻譯方式一樣',ans2:'直譯程式依行號順序翻譯並執行',ans3:'直譯程式先執行再翻譯成目的程式',ans4:'直譯程式先翻譯成目的程式，再執行之。',img:'' },
{ans:4,que:'下列那一項功能不是現代計算機之作業系統所必須具備的功能？',ans1:'分時處理',ans2:'檔案處理',ans3:'虛擬記憶體',ans4:'資料庫管理。',img:'' },
{ans:3,que:'下列那一種輸出用媒體可重複多次寫入資料',ans1:'打孔卡片',ans2:'唯讀光碟片',ans3:'CD-R/W',ans4:'微縮影片。',img:'' },
{ans:4,que:'下列何者不是系統軟體？',ans1:'作業系統(Operating Systems)',ans2:'編譯程式(Compiler)',ans3:'公用程式(Utilities)',ans4:'會計系統(Accounting Systems)。',img:'' },
{ans:3,que:'系統程式中，對原始程式翻譯與執行交替進行的是哪一個程式？',ans1:'編譯程式(Compiler)',ans2:'組譯程式(Assembler)',ans3:'直譯程式(Interpreter)',ans4:'連結載入程式(Linking Loader)。',img:'' },
{ans:4,que:'假設某城市有一萬個市民，今市政府想要將所有市民之戶籍資料電腦化，若每一位市民的戶籍資料佔用1024個位元組，請問至少需要多少張容量為1.2MB(Mega Bytes)的磁片才足以儲存所有市民的戶籍資料？',ans1:'5',ans2:'6',ans3:'7',ans4:'9。',img:'' },
{ans:3,que:'陣列是一組變數的集合，其具有下列何種特性？',ans1:'具有不同的資料型態，並且分散在記憶體之中',ans2:'具有相同的資料型態，並且分散在記憶體之中',ans3:'具有相同的資料型態，並且線性相鄰在記憶體之中',ans4:'具有不同的資料型態，並且線性相鄰在記憶體之中。',img:'' },
{ans:1,que:'下列語言，何者與中央處理器的關係最為密切？',ans1:'組合語言',ans2:'C 語言',ans3:'BASIC 語言',ans4:'COBOL 語言。',img:'' },
{ans:1,que:'下列語言，何者為最低階語言？',ans1:'機器語言',ans2:'組合語言',ans3:'自然語言',ans4:'C 語言。',img:'' },
{ans:1,que:'若需處理低階的位元或主記憶體內容，通常採用以下那一種語言設計程式較為理想？',ans1:'C 或組合語言',ans2:'COBOL或組合語言',ans3:'FORTRAN 或組合語言',ans4:'C 或Pascal 語言。',img:'' },
{ans:3,que:'下列那一種語言是屬物件導向程式語言？',ans1:'BASIC',ans2:'FORTRAN',ans3:'JAVA',ans4:'ALGOL。',img:'' },
{ans:3,que:'下列何者是屬於直譯式(interpretive)的高階語言？',ans1:'COBOL',ans2:'PASCAL',ans3:'BASIC',ans4:'FORTRAN。',img:'' },
{ans:4,que:'那一種電腦語言中，所用之指令是完全由0 與1 編碼而成的？',ans1:'組合語言',ans2:'BASIC 語言',ans3:'PASCAL 語言',ans4:'機器語言。',img:'' },
{ans:2,que:'下列何種語言是由0～9，A～F 組成之十六進位數字系統來表示？',ans1:'自然語言',ans2:'組合語言',ans3:'高階語言',ans4:'機器語言。',img:'' },
{ans:4,que:'下列何者不是WWW 的瀏覽器？',ans1:'Netscape 的Navigator',ans2:'Microsoft 的IE',ans3:'Mosaic',ans4:'Java。',img:'' },
{ans:1,que:'編譯程式(Compiler)將高階語言翻譯至可執行的過程中，連結程式(Linker)負責連結？',ans1:'目的程式與所需之副程式',ans2:'原始程式與目的程式',ans3:'副程式與可執行程式',ans4:'原始程式與可執行程式。',img:'' },
{ans:4,que:'下列何者為輸入、輸出裝置以及外接的輔助儲存裝置的統稱？',ans1:'控制設備',ans2:'CPU',ans3:'記憶體',ans4:'週邊設備。',img:'' },
{ans:2,que:'下列程式片段的執行結果為何？＜BR＞10 SUM=0＜BR＞20 FOR I=1 TO 10＜BR＞30 SUM=SUM+I+I＜BR＞40NEXT I＜BR＞50 PRINT SUM',ans1:'96',ans2:'110',ans3:'55',ans4:'45。',img:'' },
{ans:4,que:'在電腦語言中除了那種語言外，其餘均須經過翻譯才能為電腦所接受？',ans1:'BASIC',ans2:'C',ans3:'Assembly',ans4:'MachineLanguage。',img:'' },
{ans:1,que:'下列何者為高階語言的所具有的特性？',ans1:'易讀、易懂、易寫',ans2:'隨機種而改變',ans3:'不需經過翻譯便可執行',ans4:'執行時間最短。',img:'' },
{ans:3,que:'下列何種編碼不屬國內使用的中文內碼系統？',ans1:'BIG-5 碼',ans2:'通用碼',ans3:'EBCDIC 碼',ans4:'公會碼。',img:'' },
{ans:2,que:'下列那一種電腦高階語言，不但是結構化語言，同時具有組合語言及高階語言的優點？',ans1:'PASCAL',ans2:'C',ans3:'FORTRAN',ans4:'BASIC。',img:'' },
{ans:2,que:'在下列那一項不是高階語言（和組合語言比較）的優點？',ans1:'易學',ans2:'佔記憶體的空間小',ans3:'程式容易維護',ans4:'程式可攜性(Portability)高。',img:'' },
{ans:2,que:'下列何者為在高階程式語言中有特定意義且不得為程式設計者移作它用的文字？',ans1:'識別字',ans2:'保留字',ans3:'同義字',ans4:'敘述字。',img:'' },
{ans:3,que:'下列何者可支援多國語言的內碼？',ans1:'Binary 碼',ans2:'EBCDIC 碼',ans3:'Uni-code 碼',ans4:'BIG-5 碼。',img:'' },
{ans:2,que:'將高階語言的原始程式轉換為目的程式的程式是？',ans1:'作業系統(Operation Systems)',ans2:'編譯程式(Compilers)',ans3:'鏈結程式(Linker)',ans4:'載入程式(Loader)。',img:'' },
{ans:1,que:'那種電腦語言較適合發展系統軟體？',ans1:'C',ans2:'COBOL',ans3:'PASCAL',ans4:'FORTRAN。',img:'' },
{ans:1,que:'下列何者是教育部提供的網際網路？',ans1:'TANet',ans2:'SeedNet',ans3:'HiNet',ans4:'FidoNet。',img:'' },
{ans:1,que:'下列何者不屬於高階語言？',ans1:'ASSEMBLY',ans2:'BASIC',ans3:'PASCAL',ans4:'FORTRAN。',img:'' },
{ans:3,que:'目前中文內碼(BIG-5)中，多半採用兩個位元組，其高位元組十六進位值均大於',ans1:'10',ans2:'40',ans3:'80',ans4:'F0。',img:'' },
{ans:1,que:'下列程式語言何者以人名為命名？',ans1:'PASCAL 語言',ans2:'BASIC 語言',ans3:'JAVA 語言',ans4:'FORTRAN 語言。',img:'' },
{ans:4,que:'一般高階語言如：PASCAL 及C 等所編寫出來的程式，要經過數道程序才能轉換成可執行的機器語言程式，試問最後一道程序為？',ans1:'組譯程式(Assembler)',ans2:'編譯程式(Compiler)',ans3:'解碼程式(Decoder)',ans4:'連結程式(Linker)。',img:'' },
{ans:1,que:'下列哪一種印表機一定無法列印中文？',ans1:'菊輪式印表機',ans2:'噴墨式印表機',ans3:'雷射印表機',ans4:'點矩陣式印表機。',img:'' },
{ans:3,que:'下列何種電腦語言和人類的語言最相近，且廣為大眾所使用？',ans1:'中階語言',ans2:'組合語言',ans3:'高階語言',ans4:'機器語言。',img:'' },
{ans:2,que:'下列何者為電腦本身直接能了解的語言？',ans1:'組合語言',ans2:'機器語言',ans3:'中階語言',ans4:'高階語言。',img:'' },
{ans:3,que:'下列何者為人工智慧語言？',ans1:'FORTRAN',ans2:'Ada',ans3:'LISP',ans4:'C。',img:'' },
{ans:3,que:'下列那一種錯誤在原始程式編譯過程中會被發現？',ans1:'資料錯誤',ans2:'邏輯錯誤',ans3:'語法錯誤',ans4:'輸入錯誤。',img:'' },
{ans:4,que:'下列有關電腦語言之一般性敘述，何者有誤？',ans1:'PASCAL 是一種結構化程式語言',ans2:'C++是一種物件導向程式語言',ans3:'同樣功能的程式，以高階語言來設計通常較低階語言簡短',ans4:'同樣功能的程式，高階語言設計者之執行速度通常較低階語言快。',img:'' },
{ans:3,que:'下列何者非浮點數資料所包括的資料表示法？',ans1:'指數位元',ans2:'符號位數',ans3:'字元部份',ans4:'精確度部份。',img:'' },
{ans:1,que:'下列何者不是電腦語言？',ans1:'UNIX',ans2:'BASIC',ans3:'FORTRAN',ans4:'PASCAL。',img:'' },
{ans:2,que:'在電腦系統中，儲存程式及資料的主要單元是？',ans1:'算術及邏輯單元',ans2:'記憶單元',ans3:'輸出單元',ans4:'輸入單元。',img:'' },
{ans:2,que:'下列何者不屬於撥接用戶必要的設備？',ans1:'個人電腦',ans2:'網路卡',ans3:'數據機',ans4:'電話線路。',img:'' },
{ans:3,que:'下列何者無法加快電腦速度？',ans1:'精簡指令及電腦(RISC)',ans2:'平行處理作業',ans3:'較大尺寸顯示器',ans4:'新材料如砷化鎵(GaAS)及超導體等。',img:'' },
{ans:1,que:'下列那一種設備不屬於週邊設備？',ans1:'CPU(Central Processing Unit)',ans2:'OCR(Optical CharacterReader)',ans3:'MICR(Magnetic-Ink Character Recognition)',ans4:'COM(Computer Output Microfilm)。',img:'' },
{ans:4,que:'下列何者不屬輸入設備？',ans1:'鍵盤',ans2:'滑鼠',ans3:'光學字元辨認(OCR)',ans4:'繪圖機(Plotter)。',img:'' },
{ans:1,que:'下列何種設備不屬於輔助儲存設備？',ans1:'掃描器',ans2:'磁帶',ans3:'磁碟',ans4:'光碟。',img:'' },
{ans:4,que:'下列何者不屬於繪圖軟體？',ans1:'Corel Draw',ans2:'PhotoShop',ans3:'PhotoImpact',ans4:'Word。',img:'' },
{ans:3,que:'下列何者可以讓PC 與其他週邊設備互通訊息？',ans1:'PC-NET 卡',ans2:'PhotoShop',ans3:'RS-232 卡',ans4:'Hercules 卡。',img:'' },
{ans:2,que:'下列何者是在TCP/IP 標準協定中用以將電子郵件訊息從一台機器傳輸到另一台機器協定？',ans1:'SNMP(SimpleNetwork Management Protocol)',ans2:'SMTP(Simple Mail Transfer Protocol)',ans3:'NNTP(Network News TransferProtocol)',ans4:'POP(Post Office Protocol)。',img:'' },
{ans:2,que:'下列何種裝置不屬於中央處理單元(CPU)中之一部份？',ans1:'算術與邏輯運算單元(ALU)',ans2:'滑鼠(Mouse)',ans3:'控制單元(Control Unit)',ans4:'暫存器(Register)。',img:'' },
{ans:2,que:'電腦中的暫存器(Register)有許多不同的種類，下列何者不屬於暫存器之一種？',ans1:'程式計數器(Program Counter)',ans2:'主記憶體(Main Memory)',ans3:'累加器(Accumulator)',ans4:'堆疊指標(Stack Pointer)。',img:'' },
{ans:1,que:'在電腦硬體的組成單元中，下列何者與算術邏輯單元(ALU)合稱為中央處理單元(CPU)？',ans1:'控制單元(ControlUnit)',ans2:'輸出單元(Output Unit)',ans3:'儲存單元(Storage Unit)',ans4:'輸入單元(Input Unit)。',img:'' },
{ans:3,que:'下列何者不屬輸出設備？',ans1:'顯示器',ans2:'印表機',ans3:'條碼閱讀機',ans4:'繪圖機。',img:'' },
{ans:1,que:'下列何者對RAM 的敘述為正確？',ans1:'能讀出資料，亦能寫入資料',ans2:'只能讀出資料，不能寫入資料',ans3:'不能改變其內容',ans4:'不能讀出資料，只能寫入資料。',img:'' },
{ans:2,que:'下列輔助記憶體何者不能作隨機存取？',ans1:'磁碟',ans2:'磁帶',ans3:'光碟',ans4:'磁碟組。',img:'' },
{ans:3,que:'在Internet 中用於將字元機器名稱映射成IP 地址的系統我們稱之為？',ans1:'Router',ans2:'DTE(Data TerminalEquipment)',ans3:'DNS(Domain Name Server)',ans4:'SGMP(Simple Gateway Monitoring Protocol)。',img:'' },
{ans:1,que:'計算機內部執行一條指令的時間稱為？',ans1:'機器週期(Machine Cycle)',ans2:'抓取週期(FetchCycle)',ans3:'執行週期(ExecutionCycle)',ans4:'等待週期(Wait Cycle)。',img:'' },
{ans:2,que:'下列何者是在網際網路上所採用的通訊協定？',ans1:'IPX',ans2:'TCP/IP',ans3:'NETBUEI',ans4:'.X25。',img:'' },
{ans:2,que:'在電腦之硬體架構中，何者負責接受命令及解釋命令？',ans1:'輸入單元',ans2:'控制單元',ans3:'算術及邏輯單元',ans4:'記憶單元。',img:'' },
{ans:3,que:'有一微電腦，在記憶體位置上可以儲存一個8 位元資料，若記憶體位址範圍由0000 到FFFF 則記憶位址有多少位元組？',ans1:'1MB',ans2:'16MB',ans3:'64MB',ans4:'128MB。',img:'' },
{ans:3,que:'Windows XP 檔案系統所支援的檔名格式下列何者錯誤？',ans1:'檔名最長為255 個字元',ans2:'檔名中間可用多個句點隔開',ans3:'檔名中不可以有空白',ans4:'可用中、英文字元。',img:'' },
{ans:2,que:'在Windows XP 中，按下[Print Screen]鍵後，下列敘述何者正確？',ans1:'將顯示器目前所顯示的畫面由印表機印出',ans2:'將顯示器目前所顯示的畫面儲存至剪貼簿',ans3:'將目前執行的視窗儲存至剪貼簿',ans4:'無作用。',img:'' },
{ans:2,que:'一般所謂的CAD 是指下列何者？',ans1:'電腦輔助教學',ans2:'電腦輔助設計',ans3:'電腦輔助製造',ans4:'電腦輔助處理。',img:'' },
{ans:4,que:'在Windows 98 中，欲更改某個檔案屬性為唯讀狀態，應在選取該檔案後，開啟快顯功能表的何項指令進行更改：',ans1:'開啟舊檔',ans2:'建立捷徑',ans3:'重新命名',ans4:'內容。',img:'' },
{ans:1,que:'在Windows 98 中，將一文件檔案拖曳至「我的文件夾」圖示時，會產生哪一個結果：',ans1:'文件檔案被複製',ans2:'文件檔案被印出',ans3:'文件檔案會消失',ans4:'文件檔案被更新。',img:'' },
{ans:1,que:'在Windows 98 中，若要同時調整系統日期、時間，應如何操作？',ans1:'執行「控制台/日期時間」',ans2:'執行DATE 指令',ans3:'執行TIME 指令',ans4:'在桌面上按滑鼠右鍵，設定內容。',img:'' },
{ans:3,que:'在Windows 98 中，工作列的大小最大可設定為：',ans1:'可容納二排圖示',ans2:'與桌面一樣大',ans3:'桌面的一半大小',ans4:'無限制。',img:'' },
{ans:4,que:'個人電腦要支援隨插即用(Plug and Play)架構與哪一個元件無關？',ans1:'BIOS',ans2:'作業系統',ans3:'裝置及驅動程式',ans4:'應用程式。',img:'' },
{ans:1,que:'使用Windows 98 裝置管理員來查看週邊裝置時，若某個裝置旁邊出現了一個驚嘆號，表示：',ans1:'該裝置無法正常運作',ans2:'該裝置已被移除',ans3:'該裝置是針對Windows 98 特別設計的',ans4:'該裝置正以16 位元的方式在運作。',img:'' },
{ans:2,que:'在Windows 98 的電腦內，下列何者可修復FAT(File Allocation Table)？',ans1:'Chkdsk',ans2:'Scandisk',ans3:'Sys',ans4:'Edit。',img:'' },
{ans:4,que:'在Windows 98 中，不可執行那一種程式？',ans1:'32 位元Windows 程式',ans2:'16 位元Windows 程式',ans3:'MS-DOS 程式',ans4:'Macintosh 程式。',img:'' },
{ans:1,que:'Windows 98 中的「CD 播放程式」可播放：',ans1:'音樂CD',ans2:'LD',ans3:'磁片',ans4:'錄音帶。',img:'' },
{ans:3,que:'下列何者為不必親自到學校上課，而可以在家中透過網路選讀課程的上課方式？',ans1:'電腦輔助教學',ans2:'臨場教學',ans3:'遠距教學',ans4:'快速教學。',img:'' },
{ans:3,que:'在Windows 98 中查看目前機器的IP，Net mask，Default Gateway 等設定，可使用下列那一個軟體？',ans1:'Netstat',ans2:'Ping',ans3:'Winipcfg',ans4:'Route。',img:'' },
{ans:1,que:'Windows XP 具有自訂工作列的功能，而工作列右方的那一圖示可以自訂其行為，隱藏非使用中的圖示？',ans1:'TrayIcon',ans2:'Test Icon',ans3:'MSN Icon',ans4:'Setup Icon。',img:'' },
{ans:2,que:'有關Windows XP 專業版下列何者敘述錯誤？',ans1:'升級的對象為Windows 2000 使用者',ans2:'升級的對象則是WindowsMe 的使用者',ans3:'主要針對企業',ans4:'主要針對是玩家級的個人使用者。',img:'' },
{ans:3,que:'Java 程式語言是一種？',ans1:'函數語言(Functional Language)',ans2:'邏輯語言(Logical Language)',ans3:'物件導向語言(Object-Oriented Language)',ans4:'機器語言(Machine Language)。',img:'' },
{ans:3,que:'一般所謂的LAN(Local Area Network)，其所表示的意義為何？',ans1:'加值型服務網路',ans2:'整體服務網路',ans3:'區域網路',ans4:'廣域網路。',img:'' },
{ans:1,que:'ActiveX 是下列那一個公司發展出來的技術：',ans1:'微軟(Microsoft)',ans2:'IBM',ans3:'AT&T',ans4:'昇陽(SUN)。',img:'' },
{ans:1,que:'下列何種通訊協定規範全球資訊網（WWW）的通訊？',ans1:'HTTP(Hyper Text Transfer Protocol)',ans2:'SMTP(Simple MailTransfer Protocol)',ans3:'FTP(File Transfer Protocol)',ans4:'PPP(Point to Point Protocol)。',img:'' },
{ans:3,que:'下列何種通訊協定規範網際網路上的檔案傳輸？',ans1:'HTTP(Hyper Text Transfer Protocol)',ans2:'SMTP(Simple MailTransfer Protocol)',ans3:'FTP(File Transfer Protocol)',ans4:'PPP(Point to Point Protocol)。',img:'' },
{ans:2,que:'下列何種通訊協定規範網際網路上電子郵件的傳遞？',ans1:'HTTP(Hyper Text Transfer Protocol)',ans2:'SMTP(Simple MailTransfer Protocol)',ans3:'FTP(File Transfer Protocol)',ans4:'PPP(Point to Point Protocol)。',img:'' },
{ans:1,que:'封包驅動器(Packet Driver)負責網路應用程式與下列何者間的溝通？',ans1:'網路硬體設備',ans2:'編譯程式',ans3:'其他網路應用程式',ans4:'作業系統。',img:'' },
{ans:3,que:'下列何者為在全球資訊網(World Wide Web)上為使用者展現HTML 文件的程式？',ans1:'編譯程式',ans2:'伺服器',ans3:'瀏覽器',ans4:'作業系統。',img:'' },
{ans:1,que:'下列何者為網路上兩點間在同一時間只容許單向傳遞的方式？',ans1:'半雙工(Half Duplex)',ans2:'全雙工(Full Duplex)',ans3:'超雙工(Super Duplex)',ans4:'單工(Simplex)。',img:'' },
{ans:1,que:'網景(Netscape)的通訊家(Communicator)屬於下列何者？',ans1:'瀏覽器',ans2:'伺服器',ans3:'編譯程式',ans4:'作業系統。',img:'' },
{ans:1,que:'微軟(Microsoft)的探險家(Internet Explorer)屬於下列何者？',ans1:'瀏覽器',ans2:'伺服器',ans3:'編譯程式',ans4:'作業系統。',img:'' },
{ans:3,que:'微軟(Microsoft)的FrontPage 屬於下列何者？',ans1:'作業系統',ans2:'瀏覽器',ans3:'網頁製作程式',ans4:'伺服器。',img:'' },
{ans:4,que:'微軟(Microsoft)的IIS 屬於下列何者？',ans1:'作業系統',ans2:'瀏覽器',ans3:'Home Page 製作程式',ans4:'WWW 伺服器。',img:'' },
{ans:2,que:'下列何者是提供使用者網際網路服務的公司？',ans1:'IBM',ans2:'ISP',ans3:'III',ans4:'ITRI。',img:'' },
{ans:1,que:'下列何者是外接式數據機(MODEM)之連接Port？',ans1:'Serial Port',ans2:'PCI Port',ans3:'Parallel Port',ans4:'VGA Port。',img:'' },
{ans:2,que:'下列何者是製作網頁所用的主要語言？',ans1:'BASIC',ans2:'HTML',ans3:'C++',ans4:'PASCAL。',img:'' },
{ans:1,que:'瀏覽器可將首頁的內容存在何處，下次瀏覽時可節省傳遞時間？',ans1:'Cache',ans2:'CPU',ans3:'Register',ans4:'CD-ROM。',img:'' },
{ans:2,que:'在網際網路上某台電腦主機位址為www.nsc.gov.tw，則其中的gov 代表',ans1:'全球資訊網',ans2:'政府機關',ans3:'軍事單位',ans4:'教育單位。',img:'' },
{ans:4,que:'下列何者非Windows NT 支援的網路環境：',ans1:'Microsoft Network',ans2:'Novell Network',ans3:'AppleTalk Network',ans4:'VMSNetwork。',img:'' },
{ans:4,que:'下列何者非Windows NT 列印處理的服務程式：',ans1:'Spooler',ans2:'Printer Manager',ans3:'PrintProcessor',ans4:'Print Sharer。',img:'' },
{ans:4,que:'若一磁碟分割成NTFS (New Technology File Systems)，可採用下列何種作業系統存取？',ans1:'MS-DOS',ans2:'OS/2',ans3:'Windows 98',ans4:'Windows NT。',img:'' },
{ans:1,que:'若欲保護本機上使用者的檔案及目錄，應使用何種檔案系統？',ans1:'NTFS(New Technology File Systems)',ans2:'FAT(FileAllocation Table)',ans3:'HPFS(High Performance File Systems)',ans4:'FSAT(File System Allocation Table)。',img:'' },
{ans:3,que:'有關Windows XP 操作環境中，下列何者敘述錯誤？',ans1:'可以有不同的使用者設定',ans2:'以Guest 登入者表示不是該電腦的擁有者',ans3:'以Guest 登錄者，無法儲存檔案',ans4:'以Guest 登錄者，會限制使用權限。',img:'' },
{ans:4,que:'下列何者是辦公室自動化的英文簡稱？',ans1:'FA(Factory Automation)',ans2:'CA(Computer Automation)',ans3:'HA(HomeAutomation)',ans4:'OA(Office Automation)。',img:'' },
{ans:4,que:'下列何者非Windows 98 視窗環境作業系統中檔案的屬性？',ans1:'唯讀',ans2:'保存',ans3:'系統',ans4:'執行。',img:'' },
{ans:2,que:'下列何者是RS-232C 之功用之一？',ans1:'連接印表機',ans2:'連接數據機',ans3:'連接第二個螢幕',ans4:'連接硬式磁碟機。',img:'' },
{ans:1,que:'下列何者是個人電腦的冷開機與暖開機的差異？',ans1:'電腦內部的啟動方式不同',ans2:'依電腦使用時的溫度而定',ans3:'依電腦使用者熟練度而定',ans4:'沒有差別。',img:'' },
{ans:4,que:'下列何者非Windows 98 視窗環境作業系統中標準視窗組成的元素？',ans1:'功能表',ans2:'捲動軸',ans3:'標題列',ans4:'命令提示列。',img:'' },
{ans:4,que:'下列何者不屬於通訊傳輸媒介？',ans1:'光纖',ans2:'微波',ans3:'衛星',ans4:'傳真機。',img:'' },
{ans:2,que:'在Windows 98 視窗環境作業系統中若將一桌面上的視窗『縮到最小』，則在螢幕上會有何改變？',ans1:'視窗縮小到桌面上',ans2:'視窗縮小到工作列上',ans3:'視窗縮小到功能表上',ans4:'視窗縮小並隨即關閉。',img:'' },
{ans:3,que:'在Windows 98 視窗環境作業系統中若設定磁碟機為分享型態，在圖示(Icon)上會產生何種改變？',ans1:'該磁碟機圖示顏色加深',ans2:'該磁碟機圖示下方文字以框線圍住',ans3:'該磁碟機圖示出現一隻手捧住',ans4:'該磁碟機圖示出現『Sharing』文字。',img:'' },
{ans:2,que:'在Windows 98 視窗環境作業系統中，應如何選取兩個以上不連續的檔案？',ans1:'同時按住『CTRL+SHIFT』鍵再分別以滑鼠逐一點選',ans2:'按住『CTRL』鍵再分別以滑鼠逐一點選',ans3:'按住『SHIFT』鍵再分別以滑鼠逐一點選',ans4:'以滑鼠逐一點選即可。',img:'' },
{ans:2,que:'在Windows 98 視窗環境作業系統中，若選取一檔案後，按住CTRL 鍵並在同一磁碟視窗中拖曳之用途為何？',ans1:'移動檔案',ans2:'複製檔案',ans3:'移動並複製檔案',ans4:'重新排列檔案。',img:'' },
{ans:4,que:'一般所謂的WAN(Wide Area Network)，其所代表的意義為何？',ans1:'樹狀網路',ans2:'匯流排網路',ans3:'區域網路',ans4:'廣域網路。',img:'' },
{ans:4,que:'下列何者非Windows 98 視窗環境作業系統中，格式化磁片的『格式類型』？',ans1:'快速(消除)',ans2:'完整',ans3:'只複製系統檔',ans4:'只複製命令檔。',img:'' },
{ans:2,que:'市面上的商品大多貼有條碼標籤，下列哪一項設備能讀取此標籤？',ans1:'數據機',ans2:'條碼機',ans3:'光碟機',ans4:'磁碟機。',img:'' },
{ans:4,que:'下列那一項不屬於構成「整體電子商務環境」的一環？',ans1:'消費者',ans2:'金融機構',ans3:'安全認證中心',ans4:'軍事單位。',img:'' },
{ans:2,que:'視窗環境作業系統Windows 98 中，『WordPad』是屬於下列何種程式？',ans1:'造字程式',ans2:'文書處理程式',ans3:'繪圖程式',ans4:'編碼程式。',img:'' },
{ans:4,que:'以偶同位(Even Parity)錯誤偵錯法傳送7 位元資料，下列哪一項資料在傳送中發生錯誤？',ans1:'11011011',ans2:'10101010',ans3:'11001100',ans4:'10010010。',img:'' },
{ans:4,que:'下列何者非視窗環境作業系統Windows 98 中，桌面預設之圖示(Icon)或捷徑？',ans1:'我的電腦',ans2:'資源回收筒',ans3:'我的文件夾',ans4:'光碟機。',img:'' },
{ans:3,que:'下列何者非Windows 98 視窗環境作業系統中磁片格式化後所產生的摘要統計資料？',ans1:'序列號碼',ans2:'磁碟(片)空間',ans3:'命令檔所佔空間',ans4:'系統檔所佔空間。',img:'' },
{ans:4,que:'下列何者非視窗環境作業系統Windows 98 中，檔案圖示的顯示方式？',ans1:'大圖示',ans2:'小圖示',ans3:'清單',ans4:'摘要資料。',img:'' },
{ans:2,que:'下列何者非視窗環境作業系統Windows 98 中，『控制台』中的功能？',ans1:'字型',ans2:'資源回收筒',ans3:'新增/移除程式',ans4:'系統。',img:'' },
{ans:2,que:'Linux 是屬何種系統？',ans1:'應用系統(Application Systems)',ans2:'作業系統(Operation Systems)',ans3:'資料庫系統(DatabaseSystems)',ans4:'編輯系統(Editor Systems)。',img:'' },
{ans:2,que:'下列何者非視窗環境作業系統Windows 98 中內建的網路通訊協定？',ans1:'TCP/IP',ans2:'AppleTalk',ans3:'IPX/SPX',ans4:'NetBUI。',img:'' },
{ans:3,que:'PCMCIA(Personal Computer Memory Card International Association)是下列何種電腦使用的擴充介面？',ans1:'桌上型個人電腦',ans2:'工業用電腦',ans3:'筆記型電腦',ans4:'大型電腦。',img:'' },
{ans:4,que:'下列何者非CGI(Common Gateway Interface)所能提供的功能？',ans1:'取得瀏覽器傳過來的資料',ans2:'利用作業系統所提供的資源',ans3:'查詢資料庫中資料',ans4:'刪除用戶端磁碟檔案。',img:'' },
{ans:1,que:'在視窗環境作業系統Windows 98 中，『附屬應用程式』中『記事本』功能的檔案名稱為何？',ans1:'Notepad.exe',ans2:'Wordpad.exe',ans3:'Notebook.exe',ans4:'Notes.exe。',img:'' },
{ans:2,que:'在視窗環境作業系統Windows 98 中，『附屬應用程式』中『磁碟重組程式』功能的檔案名稱為何？',ans1:'Scanpst.exe',ans2:'Defrag.exe',ans3:'Drvspace.exe',ans4:'Scandskw.exe。',img:'' },
{ans:4,que:'在視窗環境作業系統Windows 98 預設中，利用鍵盤切換至其它已安裝之各種不同中文輸入法的方式為何？',ans1:'ALT+SPACE',ans2:'ALT+CTRL',ans3:'CTRL+SPACE',ans4:'CTRL+SHIFT。',img:'' },
{ans:3,que:'下列何者不是視窗環境作業系統Windows 98 中所提供的中文輸入法？',ans1:'內碼',ans2:'倉頡',ans3:'嘸蝦米',ans4:'注音。',img:'' },
{ans:3,que:'在Windows 98 中，下列哪一項不是滑鼠的使用方式？',ans1:'按一下左鍵',ans2:'連續按左鍵兩下',ans3:'連續按右鍵三下',ans4:'拖曳。',img:'' },
{ans:4,que:'下列哪一項不是Windows 98 工作列的功能？',ans1:'啟動開始功能表',ans2:'系統狀態的顯示',ans3:'程式最小化時的放置區',ans4:'做為中文輸入法的輸入區。',img:'' },
{ans:3,que:'當您新購買一部印表機時，要利用下列哪一項工具將印表機加入Windows 98 的系統內？',ans1:'檔案總管',ans2:'控制台',ans3:'我的電腦中的『印表機／新增印表機』圖示',ans4:'『桌面』上的快顯功能表。',img:'' },
{ans:4,que:'有關Windows XP 的媒體播放功能，下列敘述何者不正確？',ans1:'具有媒體導覽功能',ans2:'具有CD 燒錄功能',ans3:'具播放DVD 影片功能',ans4:'具播放DV 影片功能。',img:'' },
{ans:2,que:'Windows 98 是一個支援隨插即用(Plug-and-Play)的作業系統，一些有關硬體安裝的設定與維護都存放在那一個項目中？',ans1:'System.ini',ans2:'登錄(Registry)資料庫',ans3:'WIN.INI',ans4:'Windows98 開機磁區。',img:'' },
{ans:2,que:'下列哪一項是安裝Windows 2000 的最小記憶體需求？',ans1:'8MB',ans2:'32MB',ans3:'6MB',ans4:'16MB。',img:'' },
{ans:4,que:'下列何者不是『控制台/Internet 選項』的功能？',ans1:'代理伺服器(Proxy)設定',ans2:'網址首頁設定',ans3:'Web 網站安全性設定',ans4:'通訊協定TCP/IP 設定。',img:'' },
{ans:3,que:'在Windows 98 中，若要改變螢幕解析度，下列哪一項是正確的操作方式？',ans1:'選擇『開始』功能中的『設定』選項',ans2:'在桌面上的『我的電腦』圖示上按下滑鼠右鍵',ans3:'在『桌面』上按下滑鼠右鍵，選擇『內容』選項，然後再選擇『設定值』項目',ans4:'選擇『控制台』中的『系統』圖示。',img:'' },
{ans:1,que:'在Windows 98 中，下列哪一項操作可以在『開始』功能表中增加所需的功能表選項？',ans1:'將應用程式檔案從『檔案總管』或『我的電腦』中，直接拖曳至『工作列』上的『開始』按鈕即可',ans2:'在『桌面』上按下滑鼠右鍵，選擇『設定值』項目',ans3:'選擇『控制台』中的『系統』圖示',ans4:'選擇『開始』功能中的『設定』選項。',img:'' },
{ans:3,que:'在Windows 98 中，下列哪一項操作可以關閉在工作列上的時鐘？',ans1:'選擇『開始』功能中的『設定』選項',ans2:'選擇『控制台』中的『時間／日期』圖示，再取消『顯示小時鐘』的檢核方塊，再按下『確定』',ans3:'在『工作列』空白處，按下滑鼠右鍵，然後選擇『內容』，再取消『顯示小時鐘』的檢核方塊，再按下『確定』',ans4:'在『開始』功能表中，選擇『設定工作列』，再取消『顯示小時鐘』的檢核方塊，再按下『確定』。',img:'' },
{ans:1,que:'下列哪一項操作可以製作Windows 98 的開機片及相關系統檔案？',ans1:'選擇『控制台』中的『新增／移除程式』圖示，然後再選擇『開機片』',ans2:'在『開始』鈕上按下滑鼠右鍵，選擇『製作開機片』',ans3:'在『檔案總管』中選擇『製作開機片』',ans4:'選擇『控制台』中的『系統』圖示，然後再選擇『開機片』。',img:'' },
{ans:1,que:'在Windows 98 系統中，下列哪一項操作可以關閉當掉的應用程式？',ans1:'同時按下[Ctrl]+[Alt]+[Del]按鍵，然後結束所要關閉的應用程式',ans2:'在『控制台』中，選擇『系統』圖示，然後選擇『關閉應用程式』選項',ans3:'在『桌面』上按滑鼠右鍵，選擇『關閉應用程式』選項，然後結束所要關閉的應用程式',ans4:'在『桌面』上按滑鼠右鍵，選擇『工作管理員』，然後選擇『關閉應用程式』選項，再結束所要關閉的應用程式。',img:'' },
{ans:3,que:'下列哪一個特殊字元不是Windows 98 合法檔案名稱的字元？',ans1:'$',ans2:'@',ans3:'/',ans4:'=。',img:'' },
{ans:3,que:'在Windows 98 中，下列哪一組按鍵，可以在多個已執行的應用程式中切換？',ans1:'CTRL+ALT',ans2:'ALT+ESC',ans3:'ALT+TAB',ans4:'CTRL+ALT+ESC。',img:'' },
{ans:2,que:'在Windows XP 作業系統中刪除某個捷徑，下列哪一項說明是正確的？',ans1:'刪除捷徑後，原物件也會一併刪除',ans2:'刪除捷徑後，原物件不會被刪除',ans3:'系統不允許刪除捷徑',ans4:'必須先將原物件的檔名更改後，才可以刪除捷徑。',img:'' },
{ans:3,que:'下列何者對ICQ 的敘述有誤？',ans1:'英文縮寫為I See You',ans2:'可透過ICQ 號碼與其他人互相傳訊',ans3:'可瀏覽網站',ans4:'可傳送訊息及檔案。',img:'' },
{ans:3,que:'下列何者對匿名(Anonymous)FTP 的敘述有誤？',ans1:'登入主機可用匿名帳號FTP',ans2:'登入主機密碼為電子郵件位址',ans3:'可以下載(Download)及上傳(Upload)檔案',ans4:'可用二進位及文字模式傳送資料。',img:'' },
{ans:1,que:'下列何者對檔案檢索系統(ARCHIE)的敘述有誤？',ans1:'可用以搜尋WWW 網站',ans2:'可用以搜尋檔案資料庫',ans3:'http://archie.edu.tw 提供中文化查詢介面',ans4:'可採用WWW 及TELNET 兩種方式進行搜尋。',img:'' },
{ans:4,que:'下列何者對電子郵件(E-mail)的敘述有誤？',ans1:'可同時寄一信給多人',ans2:'可在信中加入附加檔來傳送信件',ans3:'利用SMTP 外寄主機寄信',ans4:'電子郵件帳號格式為:帳號&伺服器主機網址。',img:'' },
{ans:3,que:'下列何者對新聞群組(News Group)的敘述有誤？',ans1:'每一新聞群組最前面為國碼',ans2:'comp 群組代表電腦相關議題',ans3:'與電子佈告欄(BBS)功能完全相同',ans4:'傳輸協定為NNTP(Network NewsTransfer Protocol)。',img:'' },
{ans:3,que:'下列何者不是Internet 上所提供的服務？',ans1:'E-mail',ans2:'FTP',ans3:'CATV',ans4:'WWW。',img:'' },
{ans:4,que:'下列何者不屬於Internet？',ans1:'SEEDNet',ans2:'HiNet',ans3:'TANet',ans4:'BitNet。',img:'' },
{ans:2,que:'下列何者是用戶端接收電子郵件的傳輸協定？',ans1:'SMTP',ans2:'POP',ans3:'HTTP',ans4:'FTP。',img:'' },
{ans:4,que:'下列何者不是合法的IP 網址？',ans1:'120.80.40.20',ans2:'140.92.1.50',ans3:'192.83.166.5',ans4:'258.128.33.24。',img:'' },
{ans:1,que:'下列何者是屬於Class A 的IP 網址？',ans1:'120.80.40.20',ans2:'140.92.1.50',ans3:'192.83.166.5',ans4:'258.128.33.24。',img:'' },
{ans:2,que:'下列何者是屬於Class B 的IP 網址？',ans1:'120.80.40.20',ans2:'140.92.1.50',ans3:'192.83.166.5',ans4:'258.128.33.24。',img:'' },
{ans:3,que:'Windows XP 支援的視窗媒體音效格式稱為',ans1:'AVI',ans2:'DAT',ans3:'WMA',ans4:'WMF。',img:'' },
{ans:1,que:'下列何者是WWW 的通訊協定？',ans1:'HTTP',ans2:'GOPHER',ans3:'FTP',ans4:'TELNET。',img:'' },
{ans:3,que:'下列何者不屬於壓縮檔案的附檔名？',ans1:'arj',ans2:'exe',ans3:'txt',ans4:'zip。',img:'' },
{ans:2,que:'下列何者為HTML 標籤(Tag)？',ans1:'{P },',ans2:'＜P＞',ans3:'(P)',ans4:'[p]。',img:'' },
{ans:1,que:'下列何者為Class A 網路的IP 網址內定子網路遮罩？',ans1:'255.0.0.0',ans2:'255.255.0.0',ans3:'255.255.255.0',ans4:'255.255.255.255。',img:'' },
{ans:1,que:'Windows XP 的影片製作的軟體稱為',ans1:'Windows Movie Maker',ans2:'Media Player 8',ans3:'MediaJukebox',ans4:'Windows MediaAudio。',img:'' },
{ans:4,que:'以Windows XP 進行遠端援助時，下列那一要項不是使用者可以要求設定的？',ans1:'「使用者名稱」',ans2:'「密碼」',ans3:'「支援有效時間」',ans4:'「電器開/關時間」。',img:'' },
{ans:4,que:'下列何者不具網站搜尋功能？',ans1:'http://www.yam.com.tw/',ans2:'http://www.google.com/',ans3:'http://www.yahoo.com/',ans4:'http://archie.edu.tw/。',img:'' },
{ans:3,que:'假設有一個文字碼稱為M-code，可以包含全世界各種不同語言的文字共十萬個字，請問M-code 每一個字碼至少需要幾個bytes 才能容納這十萬個字？',ans1:'1 byte',ans2:'2 bytes',ans3:'3 bytes',ans4:'4 bytes。',img:'' },
{ans:4,que:'在Pentium 處理器中，位址匯流排有32 條，因此可以定出多少記憶體位址？',ans1:'512MB',ans2:'1GB',ans3:'2GB',ans4:'4GB。',img:'' },
{ans:1,que:'下列何者為二進位數值11001.11 的十進位數值？',ans1:'25.75',ans2:'26.25',ans3:'26.5',ans4:'21.75。',img:'' },
{ans:2,que:'請問以下哪一個儲存設備的存取速度最快？',ans1:'軟碟機(Floppy Disk)',ans2:'暫存器(Register)',ans3:'主記憶體(MainMemory)',ans4:'硬碟機(Hard Disk)。',img:'' },
{ans:3,que:'下列哪一種記憶體適合用來作為快取記憶體(Cache Memory)？',ans1:'DDR DRAM',ans2:'SDRAM',ans3:'SRAM',ans4:'EDO RAM。',img:'' },
{ans:4,que:'下列哪一種是屬於揮發性記憶體？',ans1:'Hard Disk',ans2:'Flash Memory',ans3:'ROM',ans4:'RAM。',img:'' },
{ans:1,que:'電腦主機板上的AGP 擴充槽是用來連接下列何種介面卡？',ans1:'顯示卡',ans2:'音效卡',ans3:'網路卡',ans4:'SCSI 卡。',img:'' },
{ans:2,que:'下列哪一項技術是利用硬碟空間來解決主記憶體空間不足之問題?',ans1:'快取記憶體',ans2:'虛擬記憶體',ans3:'隨機存取記憶體',ans4:'唯讀記憶體。',img:'' },
{ans:1,que:'程式計數器(PC; Program Counter)的功能是什麼？',ans1:'紀錄下一個指令的位址',ans2:'暫存指令',ans3:'控制指令執行的順序',ans4:'紀錄程式執行中的狀態資料。',img:'' },
{ans:2,que:'下列哪一項技術為一個處理器中含有兩個執行單元，可以同時執行兩個並行執行緒，以提升處理器的運算效能與多工作業的能力？',ans1:'超執行緒(Hyper Thread)',ans2:'雙核心(Dual Core)',ans3:'超純量(Super Scalar)',ans4:'單指令多資料(Single Instruction Multiple Data)。',img:'' },
{ans:1,que:'下列哪一項技術為將一個處理器模擬成多個邏輯處理器，以提升程式執行之效能？',ans1:'超執行緒(Hyper Thread)',ans2:'雙核心(Dual Core)',ans3:'超純量(Super Scalar)',ans4:'單指令多資料(Single Instruction Multiple Data)。',img:'' },
{ans:4,que:'改採用雙核心技術來提升處理器效能，可以避免用拉高處理器時脈方式(例如拉高至4GHz)提升效能所產生的問題，請問超高處理器時脈會產生的主要問題為下列何者？',ans1:'製程無法支援',ans2:'週邊設備無法支援',ans3:'溫度過高',ans4:'耗電量過高。',img:'' },
{ans:3,que:'下列哪一種介面可以讓同一程式連結到不同的資料庫來源？',ans1:'CGI',ans2:'CORBA',ans3:'ODBC',ans4:'SOAP。',img:'' },
{ans:1,que:'下列哪一種伺服器可以儲存連結網頁，提供近端存取以改善網頁存取的速度？',ans1:'Proxy Server',ans2:'MailServer',ans3:'DNS Server',ans4:'FTP Server。',img:'' },
{ans:4,que:'請問DHCP 伺服器之功能為下列何者?',ans1:'提供網路資料庫的管理功能',ans2:'提供檔案傳輸的服務',ans3:'提供網頁連結的服務',ans4:'動態的分配 IP 給使用者使用。',img:'' },
{ans:4,que:'有關於網路電話，以下哪一項敘述為錯誤的?',ans1:'VoIP 是將類比語音訊號壓縮成數位資料封包，再透過網路傳送',ans2:'Skype 是使用P2P 互通模式',ans3:'Skype 可於Windows、Linux、Mac OS、及Pocket PC 各種作業平台上執行',ans4:'Skype只能與同一個區域小範圍內的用戶互通。',img:'' },
{ans:3,que:'未來網際網路上的IP address 將採用第六版(Ipv6)，請問到時候每個IP address 總共有幾個位元組?',ans1:'4 bytes',ans2:'8bytes',ans3:'16 bytes',ans4:'20 bytes。',img:'' },
{ans:3,que:'當你旅行到國外，仍然可以使用你在台灣電信業者的帳號打手機，請問這項功能為下列何者？',ans1:'換手',ans2:'定位',ans3:'漫遊',ans4:'網外通話。',img:'' },
{ans:1,que:'GPS 在應用上的死角為下列何者？',ans1:'地下室',ans2:'公路上',ans3:'海面上',ans4:'空中。',img:'' },
{ans:1,que:'下面哪一項傳輸協定是較為安全的加密傳送協定？',ans1:'SSH',ans2:'HTTP',ans3:'FTP',ans4:'SMTP。',img:'' },
{ans:3,que:'以下對於網路防火牆的描述，何者有誤？',ans1:'能阻擋外來的入侵者對內部網路的掃瞄',ans2:'經由封包過濾可阻擋來自特定來源IP 的連線',ans3:'能有效避免員工將內部機密文件傳送出去',ans4:'應用層的防火牆可針對連線的類型(CGI)、檔案的大小等條件進行過濾。',img:'' },
{ans:4,que:'TCP/IP 最先被內建在下列哪一個作業系統中？',ans1:'Windows',ans2:'DOS',ans3:'Mac',ans4:'UNIX。',img:'' },
{ans:1,que:'請問以下哪一種無線傳輸技術的有效傳輸距離最短?',ans1:'紅外線傳輸',ans2:'藍芽技術',ans3:'無線區域網路WLAN',ans4:'超寬頻無線技術 UWB。',img:'' },
{ans:4,que:'有關於藍芽技術，下列哪一項敘述是錯誤的?',ans1:'使用廣播方式傳送，不需要對準在一直線上就能建立連線',ans2:'藍芽技術的頻寬可以達到1 Mbps',ans3:'藍芽技術的傳輸距離可以達到10 公尺',ans4:'藍芽技術的傳輸無法穿透障礙物，且無法作1 對多的短距離傳輸。',img:'' },
{ans:2,que:'以微控制器為核心，並配合適當的周邊設備，以執行特定功能，主要是用來控制、監督或輔助特定設備的裝置，其架構仍屬於一種電腦系統(包含處理器、記憶體、輸入與輸出等硬體元素)，目前最常見的應用有PDA、手機、及資訊家電，請問這種系統稱為下列何者？',ans1:'伺服器系統',ans2:'嵌入式系統',ans3:'分散式系統',ans4:'個人電腦系統。',img:'' },
{ans:4,que:'有A, B 兩個大小相同的檔案，A 檔案在硬碟中儲存在連續的位置，而B 檔案在硬碟中儲存在分散的位置，因此A 檔案的存取時間比B 檔案少，請問其主要影響因素是下列何者？',ans1:'CPU 執行時間(Execution time)',ans2:'記憶體存取時間(Memory access time)',ans3:'傳送時間(Transfer time)',ans4:'搜尋時間(Seek time)。',img:'' },
{ans:1,que:'以下有關於Cable Modem 和ADSL 寬頻上網的敘述何者有錯誤？',ans1:'Cable Modem 是專屬頻寬',ans2:'ADSL 上傳和下載的頻寬可以不同',ans3:'Cable Modem 是利用有線電視的線路上網',ans4:'ADSL 是利用現有的傳統電話線路上網。',img:'' },
{ans:1,que:'只供給台灣地區的學校與研究機關做教學研究用的網路是下列何者？',ans1:'TANet',ans2:'HiNet',ans3:'SEEDNet',ans4:'EduNet。',img:'' },
{ans:2,que:'透過Internet 在亞馬遜書店中購書，是屬於電子商務中的哪一種交易模式?',ans1:'B2B',ans2:'B2C',ans3:'C2C',ans4:'ISP。',img:'' },
{ans:3,que:'透過Internet 在eBay 網站中競標購買別人提出拍賣之蟠龍花瓶，是屬於電子商務中的哪一種交易模式?',ans1:'B2B',ans2:'B2C',ans3:'C2C',ans4:'ISP。',img:'' },
{ans:4,que:'由VISA、Master Card、Microsoft、與IBM 等公司所聯合制定的網路安全交易標準，用來保護網路上信用卡之付款交易為',ans1:'EDI',ans2:'XML',ans3:'SSL',ans4:'SET。',img:'' },
{ans:3,que:'將傳輸之資料經由鑰匙加密處理，為目前網路上受到廣泛採納的網路安全協定為',ans1:'EDI',ans2:'XML',ans3:'SSL',ans4:'SET。',img:'' },
{ans:2,que:'請問以下關於「像素（pixel）」的敘述，哪一個是「不正確」的?',ans1:'影像資料矩陣的一個元素稱為像素',ans2:'影像資料矩陣的一種顏色稱為像素',ans3:'若像素只有一個位元，則只能表現出兩種顏色',ans4:'影像能儲存的最多顏色數目，是由像素的儲存位元個數來決定。',img:'' },
{ans:4,que:'在Java 的多個版本中，哪一個版本適用於手機及PDA 上的軟體開發?',ans1:'J2EE',ans2:'J2SE',ans3:'J2PE',ans4:'J2ME。',img:'' },
{ans:1,que:'請問下列哪一種標示語言具有最大的彈性，可以允許使用者自行定義標籤?',ans1:'XML',ans2:'HTML',ans3:'WML',ans4:'VRML。',img:'' },
{ans:1,que:'在互動式網頁程式設計中，以下哪一種功能會將值寫入client 端硬碟中，以記錄客戶的各種資訊',ans1:'cookies',ans2:'session',ans3:'application',ans4:'write。',img:'' },
{ans:3,que:'有關於一般軟體系統所採用的3-Tier 元件架構，以下哪一項敘述是錯的?',ans1:'Database Server 為其中一層，用於存放及處理資料庫',ans2:'Client 端為其中一層，使用瀏覽器來執行網頁程式',ans3:'File Server 為其中一層，用於傳輸及存取檔案',ans4:'Application Server 為其中一層，用於網頁處理及應用程式之執行。',img:'' },
{ans:3,que:'以下哪一個敘述為錯誤的?',ans1:'1Byte=8bits',ans2:'1KB=2 bytes',ans3:'1MB=2 bytes',ans4:'1GB=2 bytes。',img:'' },
{ans:2,que:'以下哪一種設備，可以讓我們在只有一個IP 的狀況下，提供多部電腦上網?',ans1:'HUB 集線器',ans2:'IP 分享器',ans3:'Switch交換器',ans4:'MODEM 數據機。',img:'' },
{ans:4,que:'以下哪一種語言是專門用來處理資料庫的新增、刪除、修改、與查詢?',ans1:'UML',ans2:'LISP',ans3:'DBL',ans4:'SQL。',img:'' },
{ans:1,que:'在個人電腦上，要執行放在硬碟中的某一程式時，作業系統會先將該程式載入下列那一種記憶體裡，才開始執行？',ans1:'RAM',ans2:'EPROM',ans3:'EEPROM',ans4:'R O M。',img:'' },
{ans:4,que:'所謂「美國國家標準資訊交換碼」指的是下列那一種編碼？',ans1:'Unicode',ans2:'EBCDIC',ans3:'BIG-5',ans4:'A S C I I。',img:'' },
{ans:2,que:'下列有關記憶體的敘述，何者錯誤？',ans1:'CPU 中的暫存器執行速度比主記憶體快',ans2:'快取磁碟(Disk Cache)是利用記憶體中的快取記憶體(Cache Memory)來存放資料',ans3:'在系統軟體中，透過軟體與輔助儲存體來擴展主記憶體容量，使數個大型程式得以同時放在主記憶體內執行的技術是虛擬記憶體(Virtual Memory)',ans4:'個人電腦上大都有Level 1(L 1)及Level 2(L2)快取記憶體(Cache Memory)，其中L1 快取的速度較快，但容量較小。',img:'' },
{ans:4,que:'下列有關目錄及檔案之敘述，何者錯誤？',ans1:'磁碟格式化(Format)完成時，自動產生一層根目錄',ans2:'子目錄之下除了可以儲存檔案外，尚可包含其他子目錄',ans3:'在不同子目錄下，可以重複相同之檔案或目錄名稱',ans4:'將目錄無限制地分享他人使用，非常方便，應多加運用。',img:'' },
{ans:1,que:'下列那一種通信設備具有將數位信號、類比信號互作轉換之功能？',ans1:'數據機(Modem)',ans2:'路由器(Router)',ans3:'集線器(Hub)',ans4:'橋接器(Bridge)。',img:'' },
{ans:3,que:'下列何者屬於區域網路？',ans1:'ISDN',ans2:'Internet',ans3:'Ethernet',ans4:'Extranet。',img:'' },
{ans:3,que:'下列何者是電子資料處理的縮寫？',ans1:'ADSL',ans2:'IEEE',ans3:'EDP',ans4:'ISDN。',img:'' },
{ans:4,que:'下列何者不是檔案資料組織的方法？',ans1:'循序式(Sequential)',ans2:'索引循序式(Indexed Sequential)',ans3:'直接式(Direct)',ans4:'雜湊式(Hashing)。',img:'' },
{ans:4,que:'下列常見的電腦相關的衡量單位，何者敘述錯誤？',ans1:'衡量印表機解析度的單位是DPI (Dots Per Inch)',ans2:'磁帶資料儲存密度的單位是BPI (Bytes Per Inch)',ans3:'衡量雷射印表機列印速度的單位是PPM (Pages Per Minute)',ans4:'通訊線路傳輸速率的單位是 BPS (Bytes Per Second)。',img:'' },
{ans:1,que:'下列有關電腦語言的敘述，何者錯誤？',ans1:'高階語言程式設計比較容易，一條指令可對應多條機器語言指令，與所使用的機器有密切關係(Machine Dependent)，比較接近人們日常使用的語言',ans2:'Ｃ語言可用來撰寫Ｃ語言的編譯程式',ans3:'BASIC 屬於一種高階電腦語言',ans4:'機器語言和組合語言都屬於低階電腦語言。',img:'' },
{ans:1,que:'下列有關電腦語言的敘述，何者正確？',ans1:'BASIC 語言較不具備結構化程式的需求',ans2:'愈高階的語言撰寫之程式執行效率愈高',ans3:'高階語言不具有和低階語言一同連結(Linking)的能力',ans4:'高階電腦語言是一種不經編譯(Compilation)，就可直接執行之語言。',img:'' },
{ans:2,que:'下列那一種維護作業，對於電腦執行效能沒有幫助？',ans1:'定時執行磁碟或檔案重組',ans2:'定時執行重要檔案備份',ans3:'擴充主記憶體容量',ans4:'定時清理資源回收筒及各種過時的暫存檔。',img:'' },
{ans:3,que:'十進位數值211 可轉換成下列何者？',ans1:'二進位數值11010101',ans2:'二進位數值11100011',ans3:'十六進位數值D3',ans4:'十六進位數值E3。',img:'' },
{ans:1,que:'十六進位數值29C 可轉換成下列何者？',ans1:'八進位數值1234',ans2:'八進位數值1432',ans3:'八進位數值2134',ans4:'八進位數值4132。',img:'' },
{ans:4,que:'十六進位數值29C 可轉換成下列何者？',ans1:'十進位數值682',ans2:'十進位數值762',ans3:'十進位數值686',ans4:'十進位數值668。',img:'' },
{ans:2,que:'下列何者是作業系統的名稱？',ans1:'Oracle',ans2:'Linux',ans3:'Winzip',ans4:'BASIC。',img:'' },
{ans:3,que:'下列有關電腦中文處理的敘述，何者正確？',ans1:'列印中文必須使用雷射印表機',ans2:'同一個組織單位裡，不同的中文字可以具有相同的BIG-5 碼',ans3:'不同組織單位裡，相同的中文字可能具有不同的BIG-5 碼',ans4:'ASCII、EBCDIC、BIG-5 都是國內現行的中文內碼系統。',img:'' },
{ans:4,que:'使用於連接區域網路與廣域網路，以進行傳輸路徑選定與轉換，是下列那一種設備？',ans1:'閘道器(Gateway)',ans2:'橋接器(Bridge)',ans3:'數據機(Modem)',ans4:'路由器(Router)。',img:'' },
{ans:3,que:'下列敘述，何者錯誤？',ans1:'滑鼠、鍵盤、掃瞄機都是電腦的輸入裝置',ans2:'PC 電源開啟而螢幕無法顯示時，此現象與鍵盤之連接無關',ans3:'USB (Universal Serial Bus)與S C S I 最大外接週邊裝置數目均為1 2 7 個',ans4:'RGB 監視器(Monitor)中的R G B 是指紅綠藍三原色的意思。',img:'' },
{ans:3,que:'下列敘述，何者錯誤？',ans1:'作業系統(Operating Systems)是電腦使用者與電腦硬體之間介面程式',ans2:'作業系統之目的是為了有效率的管理電腦資源',ans3:'作業系統不能編譯程式，故不算是系統軟體',ans4:'監督程式是電腦工作管理的一環，故屬於作業系統的一部分。',img:'' },
{ans:3,que:'下列敘述，何者錯誤？',ans1:'作業系統(Operating Systems)，編譯程式(Compiler)，載入程式(Loader)，組譯程式(Assembler)都是屬於系統程式',ans2:'系統軟體主要乃協助使用者能更簡易又有效率的使用電腦系統',ans3:'電腦軟體可分為系統軟體和WINDOWS 軟體兩大類',ans4:'Unix 系統是屬於多人多工作業系統。',img:'' },
{ans:1,que:'下列敘述，何者錯誤？',ans1:'對於同一高階語言，不能同時存在有編譯程式(Compiler)及直譯程式(Interpreter)',ans2:'編譯程式(Compiler)之輸出稱之為目的程式(Object-Code)',ans3:'將程式中每一敘述逐句翻譯後，便立即執行的語言處理程式，謂之直譯程式(Interpreter)',ans4:'Java 語言是一種高階程式語言。',img:'' },
{ans:2,que:'下列敘述，何者錯誤？',ans1:'RS-232 是一種串列式資料傳輸介面',ans2:'寬頻傳輸是指傳輸速率在9600 bps 以上',ans3:'加值型網路(VAN)是指通訊網路中，提供一些資訊與服務給使用者，以提高網路價值，如金融提款系統及工商業進出口資料等',ans4:'雙絞線、同軸電纜、光纖、微波都是常用的通訊線路。',img:'' },
{ans:4,que:'下列敘述，何者正確？',ans1:'儲存資料之光碟片，可以直接用餐巾紙沾水以同心圓擦拭，以保持資料儲存良好狀況',ans2:'MO (Magnetic Optical)光碟機所使用的光碟片，外型大小及儲存容量均與CD-ROM 相同',ans3:'RAM 是一個經設計燒錄於硬體設備之記憶體',ans4:'可消除及可規劃之唯讀記憶體的縮寫為EPROM。',img:'' },
{ans:1,que:'電腦在同時段內可處理多件工作稱之為',ans1:'Multi-Tasking',ans2:'Multi-Programming',ans3:'Asynchronous TransferMode',ans4:'Multiplexing。',img:'' },
{ans:2,que:'下列敘述，何者錯誤？',ans1:'Linux 作業系統是一種多使用者(Multi-user)作業系統',ans2:'即時系統一定是連線系統，而連線系統也一定是即時系統',ans3:'Unix 系統是屬於多人多工作業系統',ans4:'Windows NT 為一先佔式多工(PreemptiveMulti-Tasking)且支援多處理器及麥金塔用戶端能力的作業系統。',img:'' },
{ans:2,que:'專門負責阻隔外部使用者不當存取公司內部資訊資源之主機稱之為',ans1:'DHCP Server',ans2:'FireWall',ans3:'HTTPServer',ans4:'Domain Name Server。',img:'' },
{ans:1,que:'下列那一個網際網路地址指的是自己這一台主機，可以公用程式ping 來測試這一台主機的網路組態是否正常？',ans1:'127.0.0.1',ans2:'172.16.0.1',ans3:'10.0.0.1',ans4:'255.255.255.0。',img:'' },
{ans:1,que:'下列電腦儲存資料所需記憶體的大小排序，何者正確？',ans1:'1TB＞1GB＞1MB＞1KB',ans2:'1KB＞1GB＞1MB＞1TB',ans3:'1GB＞1MB＞1TB＞1KB',ans4:'1TB＞1KB＞1MB＞1GB。',img:'' },
{ans:2,que:'下列何者是超大型積體電路的縮寫？',ans1:'Meta Data',ans2:'VLSI',ans3:'SMP',ans4:'NII。',img:'' },
{ans:2,que:'下列敘述，何者錯誤？',ans1:'資料通訊傳輸方式，可分為單工、半雙工及全雙工',ans2:'雷射印表機中的碳粉用完後，可購買色帶更換即可再列印',ans3:'磁柱(Cylinder)為相同半徑磁軌的集合體',ans4:'Windows 將大部分的驅動程式及應用程式訊息放到系統登錄檔(Registry)中，若要檢視或修改登錄檔中記錄的訊息，應使用工具程式Regedit。',img:'' },
{ans:2,que:'專門負責IP 位址配給賦予的主機為下列何者？',ans1:'HTTP Server',ans2:'DHCP server',ans3:'File & Printing Server',ans4:'DomainName Server。',img:'' },
{ans:2,que:'下列何者是無線感測網路的縮寫？',ans1:'WAP',ans2:'WSN',ans3:'WII',ans4:'MSN。',img:'' },
{ans:3,que:'下列何者是無線射頻識別的縮寫？',ans1:'WAP',ans2:'WSN',ans3:'RFID',ans4:'SKYPE。',img:'' },
{ans:4,que:'下列何者為「嵌入式系統開放平台(Embedded Open Platform)」？',ans1:'MSN',ans2:'SKYPE',ans3:'Openfind',ans4:'Google Android。',img:'' },
{ans:3,que:'IPv4 Address 203.66.1.2 屬於下列那一種Class？',ans1:'A',ans2:'B',ans3:'C',ans4:'D。',img:'' },
{ans:1,que:'IPv4 Address 10.0.1.2 屬於下列那一種Class？',ans1:'A',ans2:'B',ans3:'C',ans4:'D。',img:'' },
{ans:4,que:'十進位數值224 可轉換成下列何者？',ans1:'二進位數值11000100',ans2:'二進位數值10100000',ans3:'十六進位數值CD',ans4:'十六進位數值E0。',img:'' },
{ans:1,que:'八進位數值2267 可轉換成下列何者？',ans1:'十六進位數值4B7',ans2:'十六進位數值4DF',ans3:'十進位數值1745',ans4:'十進位數值1697。',img:'' },
{ans:4,que:'二進位數值0101010011000010 可轉換成下列何者？',ans1:'十六進位數值54D2',ans2:'十六進位數值5402',ans3:'十進位數值22408',ans4:'十進位數值21698。',img:'' }]