// JavaScript Document
que2=[{ans:2,que:'在BASIC 語言中，若要求Ｘ值至小數點第一位（即第二位四捨五入），應用下列何敘述？',ans1:'X=INT(X*10)/10',ans2:'X=INT(X*10＋0.5)/10',ans3:'X=INT(X*10)＋0.5/10',ans4:'X=INT(X*100)＋0.5/100。',img:'' },
{ans:3,que:'有一 BASIC 函數程式如下，試問執行後結果為何？',ans1:'0',ans2:'12',ans3:'60',ans4:'不能做。',img:'2-2.jpg' },
{ans:2,que:'下列BASIC 程式執行結果為何？',ans1:'36',ans2:'38',ans3:'40',ans4:'42。',img:'2-3.jpg' },
{ans:1,que:'在BASIC 語言中，使用函數指令RIGHT$(A$,N)相當於使用',ans1:'MID$(A$, LEN(A$)-N+1 , N)',ans2:'MID$(A$, 1 ,N)',ans3:'MID$(A$,N ,1)',ans4:'MID$(A$, N-1 , N)。',img:'' },
{ans:3,que:'在BASIC 語言中，若K=INT(90*RND)+10，則K 之範圍為何？',ans1:'1≦K≦90',ans2:'10≦K≦90',ans3:'10≦K≦99',ans4:'1≦K≦100。',img:'' },
{ans:3,que:'下列BASIC 語言程式執行結果為何？',ans1:'39',ans2:'53',ans3:'56',ans4:'1439。',img:'2-6.jpg' },
{ans:3,que:'下列BASIC 程式片段，執行後輸出結果為何？',ans1:'2.6',ans2:'52.6',ans3:'52',ans4:'53。',img:'2-7.jpg' },
{ans:2,que:'下列取整數的INT 函數運算何者有誤？',ans1:'INT',ans2:'輸出值為2',ans2:'INT(-1.9)輸出值為-1',ans3:'INT(1.9)輸出值為1',ans4:'INT(2.1)輸出值為2。',img:'' },
{ans:1,que:'下列BASIC 程式執行的結果為何？',ans1:'-5',ans2:'5',ans3:'-15',ans4:'15。',img:'2-9.jpg' },
{ans:1,que:'下列BASIC 程式的執行結果為何？',ans1:'+A+BC+DEF+',ans2:'_A+BC+DEF_',ans3:'A+BC+DEF',ans4:'無窮迴圈。',img:'2-10.jpg' },
{ans:2,que:'下列BASIC 程式執行後，顯示為何？',ans1:'ORNI',ans2:'RNIN',ans3:'NING',ans4:'ING！。',img:'2-11.jpg' },
{ans:4,que:'在BASIC 語言中，若 X$="ABCDE" 則下列何者正確？',ans1:'LEFT$(X$,2)=MID$(X$,2,4)',ans2:'RIGHT$(X$,2)=MID$(X$,2,4)',ans3:'LEFT$(X$,2)=MID$(X$,4,2)',ans4:'RIGHT$(X$,2)=MID$(X$,4,2)。',img:'' },
{ans:2,que:'下列BASIC 程式執行後，印出結果為何？',ans1:'ABC',ans2:'AAA',ans3:'ABB',ans4:'AAE。',img:'2-13.jpg' },
{ans:1,que:'下列BASIC 程式執行後，字串變數B$之內容為何？',ans1:'ABCDEA',ans2:'ABCDEE',ans3:'ABCDEABCDE',ans4:'ABCDEEDCBA。',img:'2-14.jpg' },
{ans:2,que:'下列BASIC 程式片段，執行後結果顯示為？',ans1:'P4.5',ans2:'111',ans3:'NES111',ans4:'JON。',img:'2-15.jpg' },
{ans:1,que:'在BASIC 語言中，下列何者為PRINT CHR$(48)的結果？',ans1:'0',ans2:'1',ans3:'48',ans4:'49。',img:'' },
{ans:4,que:'下列BASIC 語言程式片段，其執行結果為何？',ans1:'234',ans2:'4567',ans3:'567',ans4:'456。',img:'2-17.jpg' },
{ans:1,que:'下列BASIC 語言程式片段，其執行結果為何？',ans1:'COMP',ans2:'UTER',ans3:'COMPUTER',ans4:'COMPUT。',img:'2-18.jpg' },
{ans:2,que:'下列BASIC 語言程式片段，其執行結果為何 ？',ans1:'"97"',ans2:'"7 4"',ans3:'"748"',ans4:'"48"。',img:'2-19.jpg' },
{ans:2,que:'下列BASIC 語言程式片段，其執行結果為何？',ans1:'"2D"',ans2:'23',ans3:'"23"',ans4:'123。',img:'2-20.jpg' },
{ans:2,que:'在BASIC 語言中，下列何者為PRINT MID$("資料處理科Happy",7,6)結果？',ans1:'appy',ans2:'理科Ha',ans3:'科Happy',ans4:'Error。',img:'' },
{ans:2,que:'若兩函數定義如下，假設字串 A="123", 字串 B="4567"，當執行 STRCPY(A,B)後，再執行 STRLEN',ans1:'，則其值為何？',ans1:'3',ans2:'4',ans3:'4567',ans4:'123。',img:'2-22.jpg' },
{ans:3,que:'下列運算何者可處理兩個字串變數，而無法處理兩個數字變數？',ans1:'大小比較',ans2:'相等比較',ans3:'直接連鎖(Concatenation)合成',ans4:'邏輯運算。',img:'' },
{ans:3,que:'在BASIC 語言中，若字串變數A$中之值為"ABCDEF"，而字串變數B 中之值為"WXYZ"，則MID$(A$,3,2)+MID$(B$,2,2)之結果為？',ans1:'ABCWX',ans2:'DEFYZ',ans3:'CDXY',ans4:'DEYZ。',img:'' },
{ans:2,que:'下列BASIC 語言程式片段，其執行的結果為何？',ans1:'COMAL',ans2:'PETER',ans3:'RSONALPUTER',ans4:'TERPE。',img:'2-25.jpg' },
{ans:3,que:'在BASIC 語言中，若TEL 檔案已有2 筆記錄，下面程式執行後，TEL 檔案會有幾筆記錄？',ans1:'1 筆',ans2:'2 筆',ans3:'3 筆',ans4:'4 筆。',img:'2-26.jpg' },
{ans:1,que:'在BASIC 語言中，下述程式片段之用途為何？',ans1:'循序檔建檔',ans2:'循序檔新增資料',ans3:'隨機檔建檔',ans4:'隨機檔新增資料。',img:'2-27.jpg' },
{ans:1,que:'在BASIC 程式中讀取已開啟之循序檔資料，須用那一個函數測試檔案中資料已被讀完？',ans1:'EOF()',ans2:'LOF()',ans3:'LOC()',ans4:'FREE()。',img:'' },
{ans:4,que:'對於下列BASIC 語言程式片段，何者敘述有誤？',ans1:'共執行9 次',ans2:'列印順序為 -1, -0.5, 0, 0.5, 1, 1.5, 2, 2.5, 3',ans3:'STEP 為0.5',ans4:'當A=1，B=1 時，迴圈執行一次。',img:'2-29.jpg' },
{ans:1,que:'現有 BASIC 程式如下，請問針對各行之說明何者是錯誤的？',ans1:'行10：開啟一新檔案，名稱為DEMO，作為輸入檔',ans2:'行20：由鍵盤輸入資料',ans3:'行30：檢查輸入之資料是否為0，以決定是否停止資料輸入',ans4:'行40：將輸入之資料寫入檔案1內。',img:'2-30.jpg' },
{ans:2,que:'下列BASIC 程式執行的結果為何？',ans1:'45',ans2:'18',ans3:'9',ans4:'27。',img:'2-31.jpg' },
{ans:4,que:'欲將一檔案COPY 到另一個檔案，下列那一項操作不需執行？',ans1:'開啟檔案',ans2:'關閉檔案',ans3:'檔案讀寫',ans4:'檔案內容搜尋。',img:'' },
{ans:2,que:'下列BASIC 程式執行的結果為何？',ans1:'55',ans2:'25',ans3:'110',ans4:'30。',img:'2-33.jpg' },
{ans:4,que:'在BASIC 語言中，要在現有循序資料檔之後加入一筆新記錄，則開啟資料檔時，應指定其為哪一類型的處理方式？',ans1:'INPUT',ans2:'OUTPUT',ans3:'UPDATE',ans4:'APPEND。',img:'' },
{ans:4,que:'在BASIC 語言中，對於CHAIN 及RUN 的敘述，下列何者有誤？',ans1:'執行RUN 時，會先關閉所有已開啟的檔案',ans2:'執行RUN 時，會先清除原先程式所占用的記憶體',ans3:'執行CHAIN 時，原先的程式所開啟的檔案不會被關閉',ans4:'執行CHAIN 時，當程式執行完畢後，會返回原程式。',img:'' },
{ans:1,que:'下列BASIC 程式片段中，下列何者為其輸出結果及 SWAP A(I), A(J',img:'2-36.jpg' },
{ans:1,que:'下列BASIC 程式執行的結果為何？',ans1:'10',ans2:'9',ans3:'8',ans4:'11。',img:'2-37.jpg' },
{ans:4,que:'下列BASIC 程式執行的結果為何？',ans1:'10',ans2:'12',ans3:'9',ans4:'11。',img:'2-38.jpg' },
{ans:3,que:'下列BASIC 程式執行的結果為何？',ans1:'40',ans2:'45',ans3:'55',ans4:'60。',img:'2-39.jpg' },
{ans:4,que:'下列BASIC 程式執行的結果為何？',ans1:'5 5 0',ans2:'4 2 4',ans3:'2 4 4',ans4:'4 4 2。',img:'2-40.jpg' },
{ans:3,que:'下列BASIC 程式執行的結果為何？',ans1:'1 1 1',ans2:'2 2 2',ans3:'1 2 3',ans4:'3 3 3。',img:'2-41.jpg' },
{ans:4,que:'下列何者非BASIC 語言檔案處理指令？',ans1:'PUT',ans2:'OPEN',ans3:'CLOSE',ans4:'READ。',img:'' },
{ans:4,que:'此程式片段執行完畢後，試問 A',ans2:'之值為何？',ans1:'5',ans2:'9',ans3:'2',ans4:'8。',img:'2-43.jpg' },
{ans:2,que:'下列BASIC 語言程式片段為一排序程式，若S 陣列中之元素個數為10 個(N=10)，則上述程式之比較動作共作了幾次？',ans1:'10',ans2:'45',ans3:'55',ans4:'100。',img:'2-44.jpg' },
{ans:3,que:'下為一使用虛擬碼(PSEUDO CODE)所撰寫之程式，當N 值為何時，程式會有問題？',ans1:'N＞0',ans2:'N=0',ans3:'N＜0',ans4:'N＞=0。',img:'2-45.jpg' },
{ans:3,que:'下列BASIC 語言程式執行結束後，BEEP 指令共執行了幾次？',ans1:'3',ans2:'6',ans3:'9',ans4:'0。',img:'2-46.jpg' },
{ans:2,que:'下列何者非BASIC 語言迴圈控制指令？',ans1:'FOR...NEXT',ans2:'SWITCH...CASE',ans3:'DO WHILE...LOOP',ans4:'DO UNTIL...LOOP。',img:'' },
{ans:2,que:'下列BASIC 程式執行時會發生何種錯誤？',ans1:'OUT OF DATA IN LINE 30',ans2:'SUBSCRIPT OUT OF RANGE IN LINE 30',ans3:'OUTOF MEMORY IN LINE 30',ans4:'SYNTAX ERROR IN LINE 30。',img:'2-48.jpg' },
{ans:4,que:'若計算X,Y,Z 的總和，並把值指定給T，請問在BASIC 語言程式中，LET T=X-Y-Z 犯了何種錯誤？',ans1:'文法錯誤',ans2:'執行錯誤',ans3:'編譯錯誤',ans4:'邏輯錯誤。',img:'' },
{ans:1,que:'下列 BASIC 語言程式片段，若執行時 A=1 結果為何？',ans1:'A',ans2:'B',ans3:'C',ans4:'ABC。',img:'2-50.jpg' },
{ans:3,que:'下列BASIC 程式中，陣列A 佔幾個元素(Elements)？',ans1:'2',ans2:'3',ans3:'6',ans4:'12。',img:'2-51.jpg' },
{ans:2,que:'在BASIC 語言中，若宣告DIM A(2, 3, 4, 5)，下列何者有誤？',ans1:'與OPTION BASE 0 : DIM A(2, 3, 4, 5)同義',ans2:'共含120 個元素',ans3:'為單精度陣列',ans4:'與DIM A!(2, 3, 4, 5)意義相同。',img:'' },
{ans:1,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'185',ans2:'195',ans3:'325',ans4:'365。',img:'2-53.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'130',ans2:'146',ans3:'156',ans4:'306。',img:'2-54.jpg' },
{ans:4,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'8',ans2:'10',ans3:'12',ans4:'14。',img:'2-55.jpg' },
{ans:2,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'58',ans2:'52',ans3:'120',ans4:'110。',img:'2-56.jpg' },
{ans:4,que:'在BASIC 語言程式中，宣告陣列DIM A!(5)佔多少位元(Bytes)？',ans1:'10',ans2:'12',ans3:'20',ans4:'24。',img:'' },
{ans:2,que:'下列BASIC 語言程式，其程式功能為何？',ans1:'各數之總和',ans2:'各數之平均',ans3:'各數之值',ans4:'各數之差。',img:'2-58.jpg' },
{ans:4,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'6',ans2:'8',ans3:'3',ans4:'9。',img:'2-59.jpg' },
{ans:4,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'14',ans2:'15',ans3:'20',ans4:'21。',img:'2-60.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'4, 0',ans2:'6, 0',ans3:'0, -7',ans4:'0, -4。',img:'2-61.jpg' },
{ans:4,que:'在BASIC 語言程式中，若未設定OPTION BASE，則DIM (5, 3)敘述會在記憶體中預留多少個陣列元素的存放空間？',ans1:'8',ans2:'10',ans3:'15',ans4:'24。',img:'' },
{ans:2,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'30',ans2:'10',ans3:'40',ans4:'20。',img:'2-63.jpg' },
{ans:4,que:'下列BASIC 語言程式執行結束後，何者與A(1, 3)之值相同？',ans1:'A(2, 1)',ans2:'A(2, 2)',ans3:'A(2, 3)',ans4:'A(3, 1)。',img:'2-64.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'24',ans2:'10',ans3:'0',ans4:'1。',img:'2-65.jpg' },
{ans:2,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'55',ans2:'45',ans3:'65',ans4:'50。',img:'2-66.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'55',ans2:'45',ans3:'0',ans4:'1。',img:'2-67.jpg' },
{ans:1,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'55',ans2:'45',ans3:'65',ans4:'50。',img:'2-68.jpg' },
{ans:4,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'50',ans2:'45',ans3:'65',ans4:'55。',img:'2-69.jpg' },
{ans:2,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'55',ans2:'45',ans3:'65',ans4:'50。',img:'2-70.jpg' },
{ans:4,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'55',ans2:'45',ans3:'1',ans4:'0。',img:'2-71.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'32',ans2:'16',ans3:'0',ans4:'-16。',img:'2-72.jpg' },
{ans:2,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'30',ans2:'32',ans3:'0',ans4:'-32。',img:'2-73.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'5',ans2:'10',ans3:'15',ans4:'20。',img:'2-74.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'78',ans2:'116',ans3:'153',ans4:'168。',img:'2-75.jpg' },
{ans:1,que:'在BASIC 語言中，對WHILE...WEND 之敘述，下列何者有誤？',ans1:'若條件不成立時則重複執行某些敘述',ans2:'每執行前即判定條件',ans3:'可能執行無限多次',ans4:'可能一次都不執行。',img:'' },
{ans:4,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'25',ans2:'55',ans3:'100',ans4:'120。',img:'2-77.jpg' },
{ans:3,que:'下列何者為BASIC 語言之迴圈指令？',ans1:'IF...THEN',ans2:'GOTO',ans3:'FOR...NEXT',ans4:'GOSUB...RETURN。',img:'' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'2',ans2:'4',ans3:'3',ans4:'6。',img:'2-79.jpg' },
{ans:3,que:'下列BASIC 語言程式，其執行結果為何？',ans1:'200, 100, 300, 400',ans2:'100, 200, 300, 400',ans3:'400, 300, 200, 100',ans4:'400, 200, 100, 300。',img:'2-80.jpg' },
{ans:1,que:'下列流程圖所對應的BASIC 語言為何？',ans1:'DO ...LOOP WHILE',ans2:'WHILE...WEND',ans3:'GOTO',ans4:'IF...THEN...ELSE。',img:'2-81.jpg' },
{ans:4,que:'下列流程圖所對應的BASIC 語言為何？',ans1:'GOSUB',ans2:'GOTO',ans3:'FOR...NEXT',ans4:'IF...THEN...ELSE...。',img:'2-82.jpg' },
{ans:3,que:'下列流程圖所對應的BASIC 語言為何？',ans1:'IF...THEN...ELSE',ans2:'FOR...NEXT DO...LOOP',ans3:'WHILE...WEND',ans4:'GOTO。',img:'2-83.jpg' },
{ans:3,que:'下列流程圖所對應的BASIC 語言為何？',ans1:'DO...WHILE',ans2:'DO...LOOP',ans3:'DO...LOOP UNTIL',ans4:'CASE。',img:'2-84.jpg' },
{ans:1,que:'下列流程圖所對應的BASIC 語言為何？(A',img:'' },
{ans:4,que:'在視覺化程式語言中(如Visual Basic)中，若欲存取某一筆資料庫資料，不會使用下列何種設定？',ans1:'RecordSet',ans2:'DatabaseName',ans3:'RecordSource',ans4:'DataType。',img:'' },
{ans:4,que:'在視覺化程式語言中(如Visual Basic)中，下列何種設定無法指定表單(Form1)背景顏色？',ans1:'Form1.BackColor=&H0000ffff&',ans2:'Form1.BackColor=QBColor',ans2:'',ans3:'Form1.BackColor=RGB(250, 255,0)',ans4:'From1.BackColor=BGColor(5)。',img:'' },
{ans:4,que:'在視覺化程式語言中(如Visual Basic)中，若欲利用動態資料交換(DDE)與其它應用程式聯結時，不會使用下列何種設定？',ans1:'LinkItem',ans2:'LinkName',ans3:'LinkType',ans4:'LinkApp。',img:'' },
{ans:4,que:'在視覺化程式語言中(如Visual Basic)中，下列何種功能無法產生訊息方塊(Message Box)？',ans1:'MsgBox',ans2:'Common DialogBox',ans3:'Form',ans4:'Table。',img:'' },
{ans:1,que:'在視覺化程式語言中(如Visual Basic)中，下列何種圖形檔案格式無法處理？',ans1:'eps',ans2:'bmp',ans3:'ico',ans4:'jpg。',img:'' },
{ans:3,que:'在視覺化程式語言中(如Visual Basic)中，下列何種設定或屬性與表單大小及座標值無關？',ans1:'Left',ans2:'Right',ans3:'Enable',ans4:'ScaleMode。',img:'' },
{ans:2,que:'在視覺化程式語言(如Visual Basic)中，下列何者非滑鼠相關事件？',ans1:'Click',ans2:'KeyPress',ans3:'DragOver',ans4:'MouseMove。',img:'' },
{ans:2,que:'在視覺化程式語言中(如Visual Basic)中，若欲避免表單視窗被遮蓋後留下空白區時，則應設定下列何種屬性？',ans1:'Appearance=1',ans2:'AutoRedraw=True',ans3:'ClipControls=True',ans4:'ControlBox=True。',img:'' },
{ans:4,que:'在視覺化程式語言中(如Visual Basic)中，下列何種功能無法達成？',ans1:'動態資料交換(DDE)',ans2:'物件連結嵌入(OLE)',ans3:'資料庫連接(Database Connection)',ans4:'記憶體管理(Memory Control)。',img:'' },
{ans:3,que:'在視覺化程式語言中(如Visual Basic)中，下列何種不是物件構成基本要素？',ans1:'Method',ans2:'Property',ans3:'Field',ans4:'Event。',img:'' },
{ans:2,que:'在視覺化程式語言中(如Visual BASIC)中，下列程式用途為何？',ans1:'將滑鼠指標滑過表單時，印出Hello World!',ans2:'將滑鼠指標在表單上敲擊時，印出Hello World!',ans3:'利用鍵盤將表單拖曳時，印出Hello World!',ans4:'利用鍵盤在表單上敲擊時，印出Hello World!。',img:'2-96.jpg' },
{ans:3,que:'對C 語言的描述，下列何者有誤？',ans1:'兼具高階語言與低階語言之特性',ans2:'執行速度較一般高階語言快',ans3:'最適合作商業性資料處理之語言',ans4:'語法較接近Pascal 語言。',img:'' },
{ans:4,que:'比較C 與BASIC 語言，下列何者是C 語言特色？',ans1:'陣列',ans2:'副程式',ans3:'迴圈',ans4:'指標。',img:'' },
{ans:4,que:'對C 語言變數生命週期的敘述，下列何者正確？',ans1:'靜態變數(Static)永遠不變',ans2:'自動變數(Automatic)的宣告不佔記憶體空間',ans3:'靜態變數在該函數執行完後即消失',ans4:'自動變數在函數執行時產生，執行後消失。',img:'' },
{ans:3,que:'下列C 程式執行後顯示結果為何？',ans1:'X=0',ans2:'X=1',ans3:'X=2',ans4:'X=3。',img:'2-100.jpg' },
{ans:2,que:'在BASIC 語言中，下列何者為 PRINT ASC("A"',img:'' },
{ans:1,que:'下列 BASIC 語言程式片段，其執行結果為何？',ans1:'5',ans2:'6',ans3:'30',ans4:'40。',img:'2-102.jpg' },
{ans:4,que:'在 BASIC 語言中，若沒有特別宣告陣列 DIM A(10, 5',img:'' },
{ans:2,que:'下列是 BASIC 語言的程式片段，其執行結果為何 ?',ans1:'1',ans2:'10',ans3:'55',ans4:'65。',img:'2-104.jpg' },
{ans:2,que:'下列BASIC 程式片段，其執行結果為何？',ans1:'8',ans2:'9',ans3:'10',ans4:'11。',img:'2-105.jpg' },
{ans:2,que:'在BASIC 語言中對於變數的定義，『!』是定義單精度(Single-precision)，下列何者是定義倍精度(Double-precision)？',ans1:'@',ans2:'#',ans3:'$',ans4:'%。',img:'' },
{ans:3,que:'在BASIC 語言中，若 X$ = "abc"，則 PRINT UCASE$(X$',img:'' },
{ans:4,que:'在BASIC 語言中，下列何種指令會關閉所有的檔案並將控制權交還給作業系統？',ans1:'INPUT',ans2:'CLOSE',ans3:'EXIT',ans4:'SYSTEM。',img:'' },
{ans:1,que:'在BASIC 語言中，下列何種指令可改變系統的日期？',ans1:'DATE$',ans2:'SYSTEM$',ans3:'Time$',ans4:'SET$。',img:'' },
{ans:3,que:'在BASIC 語言中，下列何者為PRINT ABS(-36',img:'' },
{ans:3,que:'下列C 程式片段，其輸出結果為何？',ans1:'1',ans2:'1 1 1 1',ans3:'9',ans4:'9 9 9 9。',img:'2-111.jpg' },
{ans:1,que:'下列C 程式片段，其列印結果為何？',ans1:'9',ans2:'9 9',ans3:'9 9 9',ans4:'9 9 9 9。',img:'2-112.jpg' },
{ans:1,que:'在C 語言中，「*」運算符號用途為何？',ans1:'取得指標(Pointer)變數值及當成算數乘的運算符號',ans2:'取得變數位址及當成邏輯AND 的運算符號',ans3:'當字串連結運算外，亦可做數值資料加法運算',ans4:'處理緩衝區所餘存的資料及釋放檔案的通訊區域。',img:'' },
{ans:2,que:'在C 語言中，「&」運算符號用途為何？',ans1:'取得指標(Pointer)變數值及當成算數乘的運算符號',ans2:'取得變數位址及當成邏輯AND 的運算符號',ans3:'當字串連結運算外，亦可做數值資料加法運算',ans4:'處理緩衝區所餘存的資料及釋放檔案的通訊區域。',img:'' },
{ans:3,que:'在BASIC 語言中，「+」運算符號用途為何？',ans1:'取得指標(Pointer)變數值及當成算數乘的運算符號',ans2:'取得變數位址及當成邏輯AND 的運算符號',ans3:'當字串連結運算外，亦可做數值資料加法運算',ans4:'處理緩衝區所餘存的資料及釋放檔案的通訊區域。',img:'' },
{ans:1,que:'在BASIC 語言中，下列何種指令為程式執行時可刪除未開啟(OPEN)的檔案？',ans1:'KILL',ans2:'DELETE',ans3:'FREE',ans4:'DISPOSE。',img:'' },
{ans:1,que:'在BASIC 語言中，DIM SUM% 宣告與下列何者宣告效果是相同？',ans1:'DIM SUM AS INTEGER',ans2:'DIM SUM AS LONG',ans3:'DIMSUM AS FLOAT',ans4:'DIM SUM AS DOUBLE。',img:'' },
{ans:3,que:'在BASIC 語言中，若 A$ = "MyTest"，B$ = "Basic"，則 PRINT RIGHT$(A$,4)+LEFT$(B$,2',img:'' },
{ans:2,que:'在BASIC 語言中，對於變數的定義，下列何者為定義長整數(Long Integer)？',ans1:'%',ans2:'&',ans3:'$',ans4:'#。',img:'' },
{ans:1,que:'在BASIC 語言中，對於變數的定義，下列何者為定義整數(Integer)？',ans1:'%',ans2:'&',ans3:'$',ans4:'#。',img:'' },
{ans:3,que:'在BASIC 語言中，對於變數的定義，下列何者為定義字串(String)？',ans1:'%',ans2:'&',ans3:'$',ans4:'#。',img:'' },
{ans:2,que:'在BASIC 語言中，下列何者為用來定義陣列大小的指令？',ans1:'REM',ans2:'DIM',ans3:'MID',ans4:'SWAP。',img:'' },
{ans:1,que:'在BASIC 語言中，下列何者為用來註解說明的指令?',ans1:'REM',ans2:'DIM',ans3:'MID',ans4:'SWAP。',img:'' },
{ans:2,que:'在BASIC 中的隨機型檔案，將一個記錄寫入隨機檔中，應使用下列何種指令？',ans1:'WRITE',ans2:'PUT',ans3:'FLUSH',ans4:'CLEAR。',img:'' },
{ans:3,que:'在BASIC 語言中，若沒有特別宣告，陣列 DIM A(5,9)宣告了幾個元素？',ans1:'45',ans2:'46',ans3:'60',ans4:'61。',img:'' },
{ans:2,que:'在C 語言中，將一變數左移一個位元(Bit)用途為何？',ans1:'變數乘以1',ans2:'變數乘以2',ans3:'變數乘以4',ans4:'變數乘以8。',img:'' },
{ans:3,que:'在C 語言中，將一變數右移二個位元(Bit',img:'' },
{ans:3,que:'在BASIC 語言中，PRINT 19 MOD 6.7 的結果為何？',ans1:'1',ans2:'3',ans3:'5',ans4:'7。',img:'' },
{ans:4,que:'在BASIC 語言中，PRINT INSTR("Qbasic","s"',img:'' },
{ans:4,que:'在BASIC 語言中，若 X = 255，則 PRINT HEX$(X',img:'' },
{ans:2,que:'在BASIC 語言中，PRINT FIX(12.55',img:'' },
{ans:4,que:'在BASIC 語言中，PRINT CINT(12.51',img:'' },
{ans:3,que:'在BASIC 語言中，若 Y$ = "DB"，則 PRINT "*"+LTRIM$(RTRIM$(Y$))+"*"的結果為何？',ans1:'**DB',ans2:'*D*B',ans3:'*DB*',ans4:'D*B*。',img:'' },
{ans:3,que:'在BASIC 語言中，PRINT CHR$(ASC("A")',img:'' },
{ans:3,que:'在BASIC 語言中，PRINT 3/10*3 的結果為何？',ans1:'0',ans2:'0.6',ans3:'0.9',ans4:'10。',img:'' },
{ans:3,que:'在BASIC 語言中，以"$"代表字串之變數，若存在三個文字變數，A$="HI "，B$="BASIC"，C$=A$+B$，則PRINT A$+B$+C$輸出結果為何？',ans1:'HI',ans2:'BASIC',ans3:'HI BSAIC',ans4:'HI BASICHI BASIC。',img:'' },
{ans:4,que:'在BASIC 語言中，若A$="MyTest", 則PRINT RIGHT$(A$,2',img:'' },
{ans:4,que:'在BASIC 語言中，執行 PRINT ABS(36.44',img:'' },
{ans:2,que:'在BASIC 語言中， C=20 MOD 6 的結果為何？',ans1:'1',ans2:'2',ans3:'3',ans4:'4。',img:'' },
{ans:2,que:'在BASIC 語言中， PRINT(3+4*5-4)的結果為何？',ans1:'15',ans2:'19',ans3:'41',ans4:'49。',img:'' }
]